### ISSUE TITLE
add a border around inflection table cells with matching morphology

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#169]
Dependent upon https://github.com/alpheios-project/inflection-tables/issues/82

We should add a border (using the same color as used for .infl-suff--suffix-match i.e. non-exact matches) around inflection table cells with matching morphology features.

**Comment by kirlat** [comment]
Please review an implementation in https://github.com/alpheios-project/webextension/archive/comp-i169.zip

**Comment by kirlat** [comment]
I did some visual test and I'm thinking that maybe a subtle blueish background for cells might look better than a border:
![image](https://user-images.githubusercontent.com/18631055/45583560-a1fc2000-b8d5-11e8-8f81-35fcb95e989f.png)

I think a light background is less intrusive, it does distract less from the most important thing: a table content. Because it's lite, and a slightly different shade of blue than suffix matches, it will look good combined with both full and suffix matches (there are examples of both combinations on a screenshot).

The color I've used is `rgb(235, 245, 255)`, but we might try other variants too.

I was not quite happy with how the border looks now. It me it feels too rough, too intrusive to me. As a result, I decided to experiment, and want to throw this alternative solution for discussion. Please let me know what do you think.

**Comment by balmas** [comment]
Yes i like this much better!

**Comment by kirlat** [comment]
I understand that it's all very opinion based, but from my point of view a third color would make sense: we have one (yellow for an exact match), the second on is for and ending match (cyan blue), and the third one (blue or whatever we decide it to be) for a morphology match. Those three cases seems to be different to me, so they, I think, should be coded with different colors. But I might be wrong because I'm not in a position from a point of view of an Alpheios user. It's better, if possible, to see this through the eyes of Alpheios users and offer a solution that will be the best for them.

**Comment by balmas** [comment]
I am not the right person to settle a disagreement on ui design... the borders are are a little jarring to me, but I also see Monica's point about having a different paradigm than color here to represent the morphology match.  Could ask @abrasax to chime in, but not sure he will have a chance right now...

@monzug , decision on color vs border aside, as far as you can see does the functionality work?

**Comment by monzug** [comment]
YES!

**Comment by balmas** [comment]
ok, then I am going to suggest that we stick with the border for now and for @kirlat to merge this as is.

**Comment by kirlat** [comment]
OK, I will prepare a PR then.

**Comment by balmas** [comment]
now in master in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-7

**Comment by monzug** [comment]
border looks good
