### ISSUE TITLE
placeholder hint not displaying on definitions tab

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#173]
haven't debugged to see exactly why, but the placeholder text for the definitions tab isn't displaying when the tab is empty.

The test in this code is failing somewhere:

```
  <div v-show="data.shortDefinitions.length < 1 && data.fullDefinitions.length < 1" v-if="data.shortDefinitions && data.fullDefinitions">
                  {{ ln10Messages('PLACEHOLDER_DEFINITIONS') }}</div>
```

**Comment by irina060981** [comment]
As I could see from the code and from manual testing, it works correctly.

There are 2 cases here:

1) the word has morph data (and then it has a property short definition from morph data)
2) the word has no morph, than it has no properties - `data.shortDefinitions && data.fullDefinitions`

In the 1) placeholder does show at least short definitions
In the 2) placeholder doesn't render because of v-if

According to the text of the placeholder

`"message": "Lookup a word to show definitions...",`

It should be shown only when there is no word selected  - so I will change the condition here - to show placeholder when there is no selected word.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
@monzug this can now be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-3

**Comment by monzug** [comment]
this is fixed.
