### ISSUE TITLE
scrollbars appear unnecessarily in the popup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#19]
moved from https://github.com/alpheios-project/webextension/issues/58

sometimes we get a horizontal scroll bar even when there isn't anything to scroll. would be nice to eliminate this.

That's probably due to spaces before and after content that increases content's height so that it does not fit a content container. We could probably try to tweak a content height threshold to fix that in an easy way.

(to be revisited with fixes to dynamic sizing/positioning of the popup)

**Comment by balmas** [comment]
I don't know if this is still an issue at all. Assigning to @monzug to investigate.

**Comment by monzug** [comment]
lookup for virtutibus. the inflection panel has a horizontal scroll bar that could be unneeded.
see screenshot
![virtutibus](https://user-images.githubusercontent.com/41396793/59356487-ef87ab00-8cf6-11e9-8ae1-7d1dd5dec394.JPG)

**Comment by balmas** [comment]
I think the problem with the inflection table scroll bars might be the same cause as in #480, the setting of the max width for the panel of 80% of the viewport. @irina060981 can you verify? Thanks!

**Comment by irina060981** [comment]
I don't quitely understand what is wrong with scrollbars.
As I could see at the Monica's screenshot it has a horizontal scrollbar, because
  - the right padding and and right border are invisible because not enough space
  - all text in the table is very tight (headers) - so it couldn't become more narrow

@balmas , yes it has 80% from the width (as max-width) and it is used inside interact.js

May be you want to increase max width if it is needed to increase less than for example 50px?
I am not sure if interact.js could redefine it each time we have a new inflection table - should be investigated

**Comment by balmas** [comment]
>May be you want to increase max width if it is needed to increase less than for example 50px?

I don't know, it's a slippery slope. I think this probably isn't a super high priority right now. Let's defer it.

**Comment by balmas** [comment]
closing as won't fix.
