### ISSUE TITLE
there is an extra line above the Grammar in the Define section

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#237]
while testing issue #231 in Chrome, I noticed that there is an extra line above the grammar in the Define section.
see screenshot, one pop-up is in chrome and the other in firefox 
![calda-chrome-firefox](https://user-images.githubusercontent.com/41396793/46306065-2e1e7080-c581-11e8-8e3e-3f76d4b42d8f.JPG)

**Comment by balmas** [comment]
i cannot reproduce this

**Comment by monzug** [comment]
tested in Chrome latest memleak2 build.
lookup for caro and then go to define. there are some extra lines that are not visible in QA-16


![caro-line](https://user-images.githubusercontent.com/41396793/46341161-8008da00-c605-11e8-9a4e-bea83b87b5e4.JPG)

**Comment by irina060981** [comment]
@monzug and @balmas , hello!
I tried to reproduce it too (with master branches) for both words `caro` and `caldo` and there were no diffrence between layouts for  chrome and firefox.

But as I could see on one of the screenshots (with addituional spacing) there are some lines in definitions, but in chrome screenshot - there are no lines. It seems to me that there is some web-site that applies additional styles (spacing and lines) and as I tried to reproduce it on my common tests site - I couldn't see it.

Monica, on what site did you make a test with `caro` word?

**Comment by monzug** [comment]
good morning Irina,
yes, I thought it could be site related. here is the one:
http://dcc.dickinson.edu/grammar/latin/alphabet

**Comment by irina060981** [comment]
Thank you, Monica!
Now I could reproduce it :)
![image](https://user-images.githubusercontent.com/12377640/46655289-893e0c00-cbee-11e8-801f-97cd3f13860d.png)

**Comment by monzug** [comment]
it's visible also in other sites with some variation (like a dot line).
will add them when/if I come across.

**Comment by irina060981** [comment]
@balmas and @monzug ,

It is caused by using `footnotes` class in `data.fullDefinitions`
![image](https://user-images.githubusercontent.com/12377640/46655584-66602780-cbef-11e8-995f-40a9d8a2bb33.png)

And some sites are using such common class name too.

There are two ways to solve it:
1) to change common classes - `footnotes`, `entry`, `alph-source` to specific `alpheios-footnotes`, `alpheios-entry`, `alpheios-source` in the definitions sources (I really don't know if it is possible.

2) to try to analyze fullDefinitions before rendering as html and make those changes 'on the fly'

What do you think?
It seems to me that the second variant could be easier then the first :)

**Comment by balmas** [comment]
Thanks for analyzing this! We should definitely namespace the css classes used in the full definition html.  It will be pretty easy to do, actually. The source is here https://github.com/alpheios-project/lexsvc/blob/master/db/xslt/alpheios-lexi-tei.xsl. @irina060981 I don't know if you know XSLT. If you want to try to do this I'm fine with it, but you can also reassign to me if you like.

**Comment by irina060981** [comment]
Ok, I will try to do it myself :)

**Comment by balmas** [comment]
ok :-) If you want to test, you can use the docker file at https://github.com/alpheios-project/lex-docker to run a local lexicon service environment

**Comment by irina060981** [comment]
Created changes in lexsvc repo
https://github.com/alpheios-project/lexsvc/pull/4

**Comment by monzug** [comment]
@balmas do you want to add the changes in the next build?

**Comment by balmas** [comment]
there was a timing issue with releasing this because there are 2 parts to the change -- the service side for which the change was to namespace the css class names it assigns to the html elements in the lexicon response and on the extension side to use the new class names.  The webextension change made it into the 2.0.3.5 beta patch release which was published on November 5, so it should probably be safe by now to deploy the service-side change.  I will do that tomorrow morning. Thanks for the nudge!

**Comment by monzug** [comment]
one less....

**Comment by monzug** [comment]
yes. Thanks!!!
