### ISSUE TITLE
reset focus to main table after lookup

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#241]
@monzug reports that if you browse the inflection tables after doing a word lookup, with the next word lookup the focus remains on the last browsed table, rather than the table associated with the query results. We should reset the focus to the main table when showing tables for a query result.

**Comment by kirlat** [comment]
Want to clarify how to reproduce it because I cannot do that so far. What are the corrects steps? Is it:
1. Start a word lookup by clicking on a word in text or entering a word in a lookup input box (does one or the other make any difference?)
2. A popup with a word will appear.
3. Click on the "inflect" button. The panel with the first lexical query inflection table will open.
4. Click on a title of any table in an inflection browser.
5. An inflection browser table will open. A lexical query inflection table will close.
6. Close the panel.
7. Start another word lookup by clicking on a word in text or entering word in a lookup input box (does one or the other make any difference?)
8. A popup with a new word will appear.
9. Click on "inflect" button. The panel with the first lexical query related inflection table will open.

After the sequence above I see a lexical query related table displayed and inflection tables group for a language is expanded, but each individual inflection table in an inflection browser is collapsed. This seems correct to me.

**Comment by balmas** [comment]
If in step 5 you click a table that is low enough down in the window that the place for the main table scrolls out of view, at step 8, the focus stays on the (collapsed) table of contents for the browser and not on the newly opened main table

**Comment by kirlat** [comment]
Thanks for the explanation, I see it now too.
Please test a fix with https://github.com/alpheios-project/webextension/archive/comp-i241.zip.

**Comment by balmas** [comment]
@kirlat this looks good to me, please go ahead and do a PR and merge to master.

**Comment by monzug** [comment]
this is fixed. Thanks
tested in Chrome, QA-18
