### ISSUE TITLE
Diagram Panel icon is broken

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#253]
Right now, if I click on the diagram icon while viewing a diagram, it does shrink the page. Note the this icon is only available in the diagram view. Grammar, Options, define, Inflect do not have the diagram icon

**Comment by balmas** [comment]
I think this isn't working properly. It's supposed to be the icon for the panel containing the diagram, similar to grammar , etc. So that when you click on it after navigating away from the diagram you can return to it.

But as you note, it's not appearing when you actually need it, i.e. when you are on one of the other displays, and when it does appear, it has a bad effect.  Changing the title of this and making it a bug.

**Comment by irina060981** [comment]
Created PR - https://github.com/alpheios-project/components/pull/263
waiting for review

**Comment by irina060981** [comment]
Merged and closed
