### ISSUE TITLE
remove info tab from compact panel

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#339]
we are going to need to have different text and contents for the mobile version of the info component

**Comment by balmas** [comment]
the info tab in the reader application will obviate the need for the info tab on the mobile panel so changing this to request removal of the info tab from the compact panel.

**Comment by kirlat** [comment]
Since we do not have lookup in the mobile version of a toolbar (see #399), info panel is the only place from where user can start a lookup. Before we remove the info panel, we have to decide on where the lookup will go.

As was suggested in #457, we could create some kind of action panel, that will combine the lookup, the progress bar (will be shown only when lookup is in progress), and tollbar's buttons. It can be composed approximately as below:
![image](https://user-images.githubusercontent.com/18631055/56579280-d3159f00-65e0-11e9-886b-1ed5cba09e76.png)

We can display such panel in the following situations:
1. When user clicks on the floating toolbar's main button.
2. When user clicks on the menu button on a mobile panel (it can replace a mobile menu).
3. If we will have trouble fitting too many buttons into the limited width of the panel's header (as we starting to have now, with bigger buttons), we can show only most recently used there (we can make it configurable by the user so that he/she will choose which ones be shown) and add a menu-like button to the header that will call an action panel. An action panel with thus provide access to the rest of the available functionality.
4. Maybe show action panel via a right click menu.
5. We can probably use it in Alpheios Reader.

Such panel will allow us to unify our UI and solve the problem with the lookup's placement, Whenever this panel is accessible, the lookup will be available too.

Please let me know what do you think about this idea in general (regardless of what an exact layout of such panel might be). Thanks!

**Comment by balmas** [comment]
@abrasax what do you think of this suggestion?

**Comment by balmas** [comment]
I think I'd like to try this. @kirlat how much work do you think it would be to implement?

**Comment by kirlat** [comment]
Should be easy to do, but my solution can be not optimal from the standpoint of design (but we can probably fix that later).

**Comment by balmas** [comment]
Note also that we do have updated designs for the menu and panel on mobile:

https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Panel-Tool-Menu.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Mobile-Panel.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Panel-Tool-Menu.png
https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Panel-Morphology.png

**Comment by kirlat** [comment]
I've implemented a preliminary version of a panel in the `issue-comp-339-action-panel` branch. It added an action panel to the toolbar button and instead the menu of the panel on mobile. 

The idea of the panel is to keep everything a user might need conveniently in one place. So there are a lookup, a progress bar that is shown below when lookup is started, and the buttons. I removed text from the progress bar. With no text, it's takes much less space. I think text is not essential; it's pretty evident, on my opinion, whet the progress bar is for: it appears when search has started and disappears when lexical results have become available. 

We can add more data/controls to the panel if needed, it's pretty compact now.

The main advantages of the panel as I see it are:
1. It is suitable for both desktop and mobile. We can use the same familiar UI everywhere.
2. It assembles in one place everything the user might need to control an applications.

Because large version of toolbar is not needed once we have the action panel, I reduced toolbar to one button, similar to its mobile version. A click on this button opens the action panel, the other click closes it. The action panel has its own close button too.

As an alternative, we can get rid of the toolbar on mobile and attach the panel to the action in the right mouse button menu. However, we still need a toolbar button on mobile.

We can probably use the same panel to control an Alpheios reader.

I've used a layout that I think is most functional, but we can design it differently, of course, too.

Please test it when you will have time and let me know what do you think. Thanks!

**Comment by balmas** [comment]
looking at it now. I think I like it but I want to ask for some feedback from @abrasax 
A couple of things I noticed -- 
(1) I could no longer move the toolbar icon around the screen
(2) doing a lookup didn't open the panel on mobile (at least not in the emulator -- I didn't try from a real device)
(3) the word-specific icons (definition, inflection etc)  are now back -- was this intentional? I.e. do you think they should be there in this new design or was that just an oversight?

**Comment by kirlat** [comment]
This is a preliminary version, I wanted to show the idea as soon as possible without going much into details. But if you think some feature are important, please let me know and I will add them.

(1) I'm not sure if this is needed or not. I thought it might be confusing if we would have both drag and drop and click attached to the same element: a mis-implemented drag may result in a click. That might be unexpected and confusing. But I think there are ways to add drag and drop if we need it.

(2) I have not implemented that yet, but I will add it.

(3) We need them on mobile (because there's no popup there), and the idea is to have a UI that is unified across all types of devices. We removed it from the old toolbar because it took to much vertical space. With action panel being much more compact, we don't have this problem anymore. Duplication of controls (if done the right way and does not sacrifice anything) is good. It gives user a power to choose what works best for him/her. So I thought: why can't we have them on both popup and the panel? What do you think about that?

**Comment by balmas** [comment]
(1) I think it does need to be possible to move the icon around the screen, because it might be over a word and users might have preferences as to where it goes. 

(3) ok, I thought you might have had a specific reason for this :-)

No need to do anything more until I get feedback from @abrasax . Stay tuned...

**Comment by balmas** [comment]
ok, discussed with @abrasax. We want to get feedback from a few others but before doing so we would like the folloiwng changes:

(1) we want the new design to apply only on mobile, and to keep the  previous toolbar design (i.e. down the screen) on the desktop for now
(2) we still want the word-specific icons (lookup, definitions, examples, inflections) to be removed from the toolbar
(3) for now let's keep the dropdown menu and panel header on mobile as per the design at https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Panel-Tool-Menu.png and https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Panel-Morphology.png
(4) have the lookup in the mobile toolbar open the panel (as noted above)
Note that we may in fact want to use the design you suggest across all platforms but we feel like we need more feedback before we make a decision, and to do so it would be helpful to be able to have the different options as functional as possible.

**Comment by kirlat** [comment]
Thanks for the feedback, will update it tomorrow morning.

**Comment by kirlat** [comment]
@bridget, I've implemented all the suggested changes, Please let me know if I've forgetten anything.

**Comment by balmas** [comment]
ok, @kirlat can you go ahead and do a PR for this?

**Comment by kirlat** [comment]
Sure, will do that now

**Comment by balmas** [comment]
@kirlat, let's go ahead and remove the info tab from the mobile pane. Even if the final design isn't set yet, I think we have a solution that allows us to take this tab away now.

**Comment by balmas** [comment]
fixed in build 3.0.0.33 (webext)/1.0.0.11 (embedlib)

**Comment by monzug** [comment]
Info tab is gone from mobile pane.
it's still there on desktop.
