### ISSUE TITLE
Pickup text in a TinyMCE text area

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#34]
report from a user:
[Alpheios] does not seem to be able to pick up text inside of a TinyMCE text area.

Here's the TinyMCE demo page: https://www.tinymce.com/docs/demo/full-featured/

If you double click on text above the TinyMCE window, the popup appears, but not if you double click on text inside of the window.

**Comment by irina060981** [comment]
For the first look the problem is with manipulating a content of embedded cross-domain iframes.
It is restricted from browser sides.
There are some information in tis stackoverflow thread
https://stackoverflow.com/questions/42968473/firefox-webextension-how-to-obtain-and-modify-content-of-cross-domain-iframe

I tried to change permissions in manifest.json - but there were no result for this.
I will make a deeper investigation later.

**Comment by balmas** [comment]
This is then probably also related to #15 
Aside from the cross-domain issue, I think the webextension won't work in any iframe right now because the webextension content script only activates the event handlers on `document.body` of the primary document in the window.  

I would like to be able to be more flexible with this, and add the ability to activate Alpheios on the contents of any iframes embedded in the main document.   Maybe we would use the [webNavigation#getAllFrames](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webNavigation/getAllFrames) to traverse down into the documents of each frame.

**Comment by balmas** [comment]
we can close this issue , because it seems it's really just a dupe of #15
