### ISSUE TITLE
Font size inside panel-compact is scaling depending on the panel width

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#352]
@balmas and @kirlat 
There is a strange behaviour inside `panel-compact` - it is scaling font-size, paddings according to the current width of the panel.
This way the same `font-size: 16px` inside the page and inside the panel look like very different.
I didn't find out how does it work really.
Here are some screenshots:

![image](https://user-images.githubusercontent.com/12377640/54200887-17a91780-4518-11e9-80bd-c0056a01b09b.png)

![image](https://user-images.githubusercontent.com/12377640/54200902-1e378f00-4518-11e9-9e9c-49a4e01f4605.png)

![image](https://user-images.githubusercontent.com/12377640/54200934-2b547e00-4518-11e9-8d25-bd002531c011.png)

**Comment by irina060981** [comment]
Also the same problem with not compact popup:
![image](https://user-images.githubusercontent.com/12377640/54259805-ae2a1700-45b2-11e9-9f5b-d4f919672714.png)

**Comment by balmas** [comment]
I am not sure, but I think this is still a problem

**Comment by kirlat** [comment]
Started to research this and I think it's all due to browser on device zooming. Let's take for example, an LG Nexus 5 that is available within Chrome's dev tools emulator. It has a physical resolution of 1080x1920 px. Also, this device has a scaling factor 3:1 - one logical CSS pixel is represented by the three physical ones (https://blogs.perficientdigital.com/2014/12/24/css-pixel-ratio-or-how-big-is-my-phone/). So that reduces its logical CSS resolution to 360x640. This is clearly visible in the emulator's upper toolbar:
![image](https://user-images.githubusercontent.com/18631055/56968104-9e22c280-6b73-11e9-98ca-391047ded4fc.png)
If to select a root `html` element it will, however, it will be shown as having a width of 980 px. Comparing with the logical CSS width of 360 px, it gives a scaling factor of 980:360 = 2.72.

Now let's select a paragraph on the page. It has a font size equal to 16 px as set in CSS rule. However, Chrome shows that it actual font size is 43.56 px. 
![image](https://user-images.githubusercontent.com/18631055/56969070-72a0d780-6b75-11e9-83ac-727e0bf35261.png)
We see that it's the same ratio: 43.56:16 =  2.72.

So it's like the browser decided that everything will be too small if shown at 360 px and decided to scale everything up to 980px proportionally.

Right now I have no idea why is this happening, but I will continue my investigation.

**Comment by kirlat** [comment]
What's interesting, if to put device to a landscape orientation, it will still be scaled up to 980px:
![image](https://user-images.githubusercontent.com/18631055/56969242-cd3a3380-6b75-11e9-9af6-b27e2b2c8bd9.png)
However, because logical CSS width of the landsape is higher (640px), the scaling factor is smaller: 980:640 = 1.53.

A smaller font size proves that:
![image](https://user-images.githubusercontent.com/18631055/56969372-11c5cf00-6b76-11e9-924c-6bc45e4f70c2.png)
However, the font mysteriously has a slightly different aspect ratio: 26.22:16=1.64.

**Comment by balmas** [comment]
maybe we need to use this?
https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust

**Comment by kirlat** [comment]
That seems to do the trick. Not supported by Firefox and Safari on desktop, it is supported by majority of mobile browsers, where we need it most. Thanks for the clue!

**Comment by kirlat** [comment]
Verified that it is working correctly on a mobile phone

**Comment by balmas** [comment]
this can be tested in 1.0.0.7

**Comment by irina060981** [comment]
I have started to work on the issue - fix mobile layout for the word usage examples
and uploaded the last version of the `embed-lib`  with the last version of `components`
And tried to see the mobile layout
And the font-size is still very small

**Comment by irina060981** [comment]
![Screenshot_20190509-154840](https://user-images.githubusercontent.com/12377640/57430317-a0230a80-7272-11e9-96fb-c42bef7a43d1.png)

**Comment by irina060981** [comment]
I have Samsung Galaxy A5(2016)

**Comment by balmas** [comment]
I have noticed this too, but was assuming maybe it was caused by something in the embed-lib demo page because it looks different (and much better) when used on the alpheios_nemo ui.

**Comment by kirlat** [comment]
It can be affected by both the settings of the page (`viewport` meta tag, most notably: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) and the browser decision on what zoom to apply. The latter is the factor of a device, browser, and OS.

Information on the topic (zooming strategy of browsers, especially) is very scarce. Many solutions are outdated and do not work any more. We could always zoom text manually with changing the base text size CSS variable, but it can be a challenge to decide what scale shall be applied in each particular case.

I will continue to read about this and test whatever may work for us.

**Comment by balmas** [comment]
I think getting it to work on ANY page isn't really a priority. The main priorities are
(1) that it works on our pages (i.e. the alpheios_nemo ui)
(2) that we can define guidelines for any page that wants to embed it, so that they can avoid problems and conflicts

**Comment by monzug** [comment]
I don't see any issue here on iPhone xr and Samsung 5 mini on text env. @irina060981 and @balmas, have you seen any issue with font size on your devices?

**Comment by irina060981** [comment]
@monzug , this issue depends on the fact if meta tag with scaling properties is presented in the header.
I have added it to the demo/index.html in embed-lib (I am testing most of all here) and it is added to texts environment.
So it shouldn't be reproducable (I didn't see this problem again)

But we didn't test it with pages that have other scaling properties in meta tag.
This is actual only for webextension, only there we don't have a control for meta tags.

**Comment by kirlat** [comment]
> This is actual only for webextension, only there we don't have a control for meta tags.

In webextension we can inject our own viewport meta tag to control scaling, and even restore the original viewport data after extension is deactivated, but I don't know if we should go that far.

**Comment by balmas** [comment]
we should not worry about the webextension for now, since it doesn't work on mobile devices anyway.

**Comment by irina060981** [comment]
I think that it is not as easy as it expected to be.
Changing meta-tags after page is loaded won't rerender page automatically in all situations, because it is not a css.
The viewport meta tag tells the browser how to behave when it renders the webpage, you can tell it how big the viewport will be.

**Comment by monzug** [comment]
I don't see the problem on mobile. tested on balmas.github.io
