### ISSUE TITLE
we make too many calls for the grammar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#361]
everytime we do a lookup it seems the grammar toc is retrieved.

**Comment by irina060981** [comment]
The reason of such re-request of grammar is in the fact, that on each lookup request all grammar tab is fully re-rendered and iframe requests url again when it appears again on the page.

**Comment by irina060981** [comment]
I have changed the condition of updating grammar - only when language is changed.
An interesting fact - if all inner data of the vue component is absent (because of v-if), then it would ve destroyed completely and re-created when inner data will appear.

So from one point of view v-if should save the amount of data rendered in the html layout, but from the other side - it make all html layout to be recreated and pasted inside HTML, that is the heaviest operation for the browser.

**Comment by irina060981** [comment]
I have found a strange problem - that makes tabs re-render - and grammar tab is fully re-rendered despite the v-if property is not changed. Needs to be investigated more.

**Comment by irina060981** [comment]
I have found the problem - it was with passing a parameter to state mutation as a result of function - for some reasons - it makes some strange actions for state properties and made re-render tabs.
I have fixed - and now - grammar is working properly.

**Comment by irina060981** [comment]
Merged and closed!
Hope, it will solve some performance problems too :)
