### ISSUE TITLE
text environment extremely slow in Chrome

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#378]
I do not know exactly when this is happening but Alpheios got stuck several times waiting for the following api:

![slow wait for](https://user-images.githubusercontent.com/41396793/55422004-a4a82500-5548-11e9-9f80-50a7d574f61d.JPG)

I worked on wordlist mainly:
- scrolling text on same book or going back and forward from one book to an other 
- following the link in Show context and then scrolling text there

**Comment by balmas** [comment]
there is a leap in latency at around around 16:00 UTC today, but according to the log response times were still well under one second per request.

But we definitely need to be sure that slow responses from the wordlist api don't affect the overall functioning of Alpheios or the page it is being used on.  @irina060981  we may need to try to replicate some load conditions so that we can debug and understand this better.

**Comment by irina060981** [comment]
I have spent time to investigate here.
I added big timeouts to requests and made several requests one by one - to make a queue to amazon server. And it was really slowly.
But it really has no effect on the webextension and its performance - I couldn't see it.
The only problem here - that it could have not enough time to save to remote and will be lost at the future session and that's all.

I think that frozens could be not from the AWS requests.

@balmas , do you have any ideas what other experiments I could do here?

**Comment by balmas** [comment]
Maybe this was a dupe of #434 ? @monzug is this still reproducible?

**Comment by monzug** [comment]
Haven't experienced any delay lately.
