### ISSUE TITLE
verify skinning works and no conflicts between embed-lib and webextension

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#387]
Not sure yet if this is only in the embedded library or also in the extension. Here's how it looks in the embedded library in Safari

![Screenshot 2019-04-08 09 29 32](https://user-images.githubusercontent.com/644870/55728082-63e55b80-59e1-11e9-913a-fbc133f42a5a.png)

![Screenshot 2019-04-08 09 29 27](https://user-images.githubusercontent.com/644870/55728093-68117900-59e1-11e9-9de2-679b8f332b0b.png)

](url)

**Comment by balmas** [comment]
Safari Version 12.0 (14606.1.36.1.9)

**Comment by balmas** [comment]
this does seem to be limited to the embedded library because here's how it looks in the extension
![Screenshot 2019-04-08 10 03 50](https://user-images.githubusercontent.com/644870/55730199-a872f600-59e5-11e9-989e-0b4bde48470f.png)

**Comment by kirlat** [comment]
It's really strange, but I cannot reproduce it on my Mac. Here is what I did for testing: checked out latest `master` versions of `components` and `embed-lib`, rebuilt them, and run an embed lib on a dev server (i.e. `localhost:8888`). And here is what I've seen:
![image](https://user-images.githubusercontent.com/18631055/55856077-45ff2e80-5b7a-11e9-9c13-b895fff4fb05.png)
It looks quite normal, the way it should be. I'm wondering if it could be a build issue. Maybe the styles got not picked up?

It's worth noting that we've changed the way we create styles in embed-lib and webextension. Before we were taking stylesheets from components and retranspiling them. But that made no sense as webextension has no styles of its own and embed-lib does not have any currently too, but event if it does, they will be transpiled into a separate file. So now we're simply copying the stylesheets from the `components/dist/style` into the `[webextension|embed-lib]/dist/style` and then use those. Tasks for that are added into all build tasks of embed-lib and webextension. But I'm wondering maybe there is anything wrong with the copy process?

Also, if webextension is installed in Safari, it does inject its own stylesheets. One have to disable it manually in preferences. In my test I had it enabled and still was able to get correct styles on embed-lib, but I'm wondering if it might be webextension injecting some outdated styles that intefere with styles of embed-lib? That's probably not the case because webextension was displaying correct styles, but maybe its worth checking. In Safari injected stylesheets has a higher priority than in other browsers and thus they have greater powers. Also maybe there is some internal caching involved somewhere.

**Comment by balmas** [comment]
Ah, that's interesting. You are correct that the webextension styles are apparently overriding the styles of the embedded library in Safari. That is going to be problematic because we want users of the embedded library to be able to override the default styles for their page, regardless of whether a user has the Alpheios webextension installed.  I think maybe it was affecting the overlay toolbar and not the popup and panel because the embedded library uses a different parent id for those templates. So we probably need to do the same for the toolbar and maybe that will solve this?

**Comment by kirlat** [comment]
Maybe it was not the IDs (because we do not have styles tied to IDs, unless I'm wrong here), bur rather a peculiar combination of webextension and embed-lib styles that gave such a strange effect. I think that should not be a problem when CSS-defined styles of webextension and embed-lib matches each other.

Because all styles are variable based, the only important thing for the user who wants to override Alpheios styles is that CSS variables of the user must have a higher specificity than those of Alpheios-defined vars. Specificity of classes itself does not matter. And because CSS rules of both webextension and embed-lib are the same and are both variable based, they all will be changed affected by custom var values set by the user. Then it does not matter what overrides what: webextension or embed-lib. They all will be the same.

An additional benefit of that is that the user, with custom CSS props, can override styles of not embed-lib only, but ones of a webextension too. That present an easy way to customize a webextension (if we will ever need it).

**Comment by balmas** [comment]
ok. I want to leave this open to define a test case sooner rather than later for skinning the embed-lib. I will assign it to myself for now.

**Comment by balmas** [comment]
@irina060981 this might be a good one to do before vacation. I think there is a documentation component too -- documenting how to add a stylesheet which redefines the Alpheios CSS variables to a page which uses the embed-lib. What do you think?

**Comment by irina060981** [comment]
I took a real site
http://www.nationalarchives.gov.uk

created a static copy of the home page - http://alpheios-test-skin.irina-sklyarova.ru/
and tried to skinnify - and it is not as easy as I expected, because:
Variables work well, but there is no consistent branding logic for collor.

for example, We could see on this site that it is worth to use the following colors:
   for headers and toolbar backghround - #008484 (lighter blue-green)
   it uses a variable - `--alpheios-toolbar-bg-color`
   but it is not enough, because icons in the header had addional variable
       `--alpheios-icon-bg-color-hover` - that should have the same color

some parts has direct colors values - for example
it is worth to make buttons this color (red instead of orange)
    some buttons have variable `--alpheios-btn-primary-bg-color`  
    some buttons (changing font-size on options tab) - have direct variable `--alpheios-text-color-vivid`

And so on

I suggest to create skinning variables - like `--alpheios-btn-primary-bg-color`  for all tabs on the panel, for the popup, for the floating toolbar and remove all direct usage of color variable

this way we could make a skinify process only as changing values of variables that are available for skinning.
And the the main part of skinnify documentation - would be the description of variables

**Comment by irina060981** [comment]
And changing variables don't work inside Safari (on Mac)
I opened the same url - http://alpheios-test-skin.irina-sklyarova.ru/
and it sees the variables - but doesn't change the color.
@kirlat, did you test thios process on Safari? what I am doing wrong here?

**Comment by balmas** [comment]
that's strange. it does work for me on Safari.
![Screenshot 2019-07-03 07 30 39](https://user-images.githubusercontent.com/644870/60588311-a0b4ba80-9d64-11e9-8ee4-f7bdb08818db.png)

**Comment by balmas** [comment]
>I suggest to create skinning variables - like --alpheios-btn-primary-bg-color for all tabs on the panel, for the popup, for the floating toolbar and remove all direct usage of color variable

I think this is a very good idea.

**Comment by irina060981** [comment]
> that's strange. it does work for me on Safari.

this is really strange!

**Comment by balmas** [comment]
what version of Safari are you running? I haven't updated in awhile so I might be behind. I have 12.0 (14606.1.36.1.19)

**Comment by irina060981** [comment]
On Mac - where there is a bug with variables - Version 12.1.1 (13607.2.6.1.2)
But on my iPhone on Safari it works well

**Comment by balmas** [comment]
So it's a known bug?

**Comment by irina060981** [comment]
>So it's a known bug?
I am not familiar with variables - it is a new technique - will try to find some information

**Comment by balmas** [comment]
ok, I'm updating my mac now so that I can test if it still works for me in the later version of Safari.

**Comment by irina060981** [comment]
According to this - it should work https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties

and it works for initial values of variables

but may be there are some stranges with inheritance and priority
because it is not quitely known - how it uses for priorities (Safari could have another algorithm)

**Comment by irina060981** [comment]
@balmas, I was able to fix it! I have moved my new vars to `body` instead of `html`.
And now it works well on my Mac :)

**Comment by balmas** [comment]
yay!

**Comment by kirlat** [comment]
> @balmas, I was able to fix it! I have moved my new vars to `body` instead of `html`.
> And now it works well on my Mac :)

Sorry for being late into discussion, but the idea was to use `:root` pseudo-element for the variables within skins (https://developer.mozilla.org/en-US/docs/Web/CSS/:root). Default skin color vars are defined for `html` element. `:root` is pretty much the same, but with a higher priority. So defining vars for `:root` should override whatever is defined for `html`.
`body` works too, but with defining skins for `:root` we'll leave an ability to do another custom redefine (i.e. some kind of custom skin modification) by defining values for `body`.
What do you think about this approach?

**Comment by kirlat** [comment]
> I suggest to create skinning variables - like `--alpheios-btn-primary-bg-color` for all tabs on the panel, for the popup, for the floating toolbar and remove all direct usage of color variable
> 
> this way we could make a skinify process only as changing values of variables that are available for skinning.
> And the the main part of skinnify documentation - would be the description of variables

I think this is a good approach. Just redefining the brand colors, I believe, is not enough because it has to be more granular than that. The use of some color may require contrast color in some adjacent places but smoother colors in the others. So what was one color in our style guide may become two or three colors in some custom theme. Because of this, assigning a variable to each element that we want to be skinnable and giving users freedom to redefine it all the way they want is the best way to go, on my opinion.

In theory, we can use variables to let users redefine not only colors, but element sizes and other lower level details, but I don't know if there is a need to go that far.

**Comment by irina060981** [comment]
For now I am going to create/fix two layers of variables:

1 layer - will be united by the same color in our design + by the sense of layout
    (for example `--alpheios-toolbar-bg-color`) that would be used through different parts of the application
    
2 layer - variables for each customizable part - for example 
   `--alpheios-desktop-toolbar-bg`
   `--alpheios-desktop-popup-header-bg`
   `--alpheios-compact-panel-header-bg`
   and so on, and they would be equal to `--alpheios-toolbar-bg-color`

This way a developer who would create a skin , would be able to set common branding colors at the 1 layer and some exceptions using the 2 layer.

>Default skin color vars are defined for html element. :root is pretty much the same, but with a higher priority.

I would test it 
I couldn't find the link where I have found a suggestion but it was the following:
  use `:root` for initial values
  use `body` for redefining

but if you consider to use `:root`  and `html`, I believe you know better :)

**Comment by balmas** [comment]
we can close this now. the skinning doc is in the embed-lib repo.
