### ISSUE TITLE
overlay toolbar icons flashing

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#389]
why do the icons on the side navigation shrink from 7 (or  8) to 4 (or 5) while double-clicking on a new word? Define, Inflection and World usage example (if option is checked) do disappear while lexical data is loading. in look-up, only Inflection icon does briefly disappear.

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/317#issuecomment-478598646_

**Comment by balmas** [comment]
@kirlat not sure what the best solution is to make this less confusing for the user. Any thoughts?

**Comment by kirlat** [comment]
This is "by design", We do not want to show definitions/inflections/some other icons when corresponding data is not available. So when we click on a new word, old data is erased, we're loosing corresponding data, and icons are hidden. When data about the new word comes in, the icons are shown again.

Not sure what we can do here UI-wise, need to think about it. Maybe we can collapse side navigation icons when user double clicks the word? But then the user will need to reopen it again, if he or she is working the the side navigation. Not very convenient. Maybe we can reopen it automatically when lexical query is fully complete (if it was open the moment lexical request started)?

We don't have this issue with the panel because we're hiding it on every new request.

What is happening is that we reset the side navigation's state depending on the lexical request context. We probably need to indicate that to user somehow. Maybe we can put some indicator somewhere showing that the data is in the process of retrieval (but have no idea where yet)?

**Comment by kirlat** [comment]
Or, as the other option, we can not hide icons, but make them "inactive" (grayed out or something like that). Then it won't cause such visual disruptions as with icons being hidden and shown.

**Comment by balmas** [comment]
I think that might be a good compromise. @monzug what do you think?

**Comment by monzug** [comment]
agree, good idea. though the icons are already grayed out.

**Comment by kirlat** [comment]
I will do this change then.

**Comment by balmas** [comment]
can be tested in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment]
tested in chrome 3.0.0.26
worked as described.
Status message icon in the overlay is for testing, correct?
