### ISSUE TITLE
make the popup header narrower with smaller close icon

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#395]
We need the popup header to be narrower and use a smaller close icon.  A new close icon can be found at https://github.com/alpheios-project/design-guidelines/blob/master/v3/Icons/SVGs/X-Close-Icon.svg

**Comment by kirlat** [comment]
I do have some questions about this change:

(1) It's really strange, but when an SVG provided for the icon is inserted into the code, it is rendered as below by both Chrome and FF:
![image](https://user-images.githubusercontent.com/18631055/55875661-a6a46080-5ba6-11e9-9b9f-948a117d05c0.png)
I'm not sure why exactly, but probably because it has fill set to red inside the file and the stroke is white as set by our current CSS (this file does not have a stroke color defined inside). What should be the correct look of an X? Shall it be all red? If so, to what color shall it change on hover? Shall it be yellow as currently? Shall it be red an all backgrounds? On a dark blue background it seems to be hard to distinguish to me (but I might be wrong here):
![image](https://user-images.githubusercontent.com/18631055/55876485-d5233b00-5ba8-11e9-88fb-1e33c669772e.png)

(2) Shall we reduce a header height and by how much? Right now the icon itself is 44px X 44px, and that's define the height of a toolbar (it is 56px tall). Shall we reduce the size of an icon to allow for a narrower toolbar?

(3) Does the icon change affect only the popup's toolbar or shall we switch to new close icons everywhere? If so, will all of them be red too?

(4) Shall we reduce the height of a panel's toolbar as well?

**Comment by balmas** [comment]
I think the colors need to be removed from the svg so that it can be fully styled with CSS according to the styleguide

I would also like to see how it looks with a smaller icon and header size for the popup header only, keeping the panel toolbar at the current size.

**Comment by kirlat** [comment]
If it will look the way as below, will it be any good?

![image](https://user-images.githubusercontent.com/18631055/55900453-4a5a3480-5bd8-11e9-98fd-9ffe6bf5a339.png)

To see it live, please use a `comp-i395` branch.

**Comment by balmas** [comment]
let's use that for now. we may decide to switch back to the other color here

**Comment by balmas** [comment]
I think this probably isn't the final design,but this fix is in 3.0.0.26 (https://github.com/alpheios-project/webextension/tree/qa-3.0.0.26/dist and Dropbox)

**Comment by monzug** [comment]
small close icon is in.
