### ISSUE TITLE
use tertiary button style for notifications

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#396]
we should use the tertiary button style for notification messages (see styleguide)

Use alpheios-color-vivid for error notifications and alpheios-color-muted for informational notifications

**Comment by kirlat** [comment]
The problem with tertiary button is that it, on informational notifications, blends with it when hovered or pressed. It has the same color:
![image](https://user-images.githubusercontent.com/18631055/55939128-09046c00-5c4e-11e9-912a-1d6891a75d04.png)
Don't know if it's OK or not. On vivid it looks good.

**Comment by kirlat** [comment]
We do have "regular" and "important" notifications. So I've made the first one's color to be "alpheios-color-muted" and the second one's "alpheios-color-vivid". I think we probably can use "important" notifications to show errors and don't need a special error class. What's your opinion on that?

**Comment by kirlat** [comment]
Implemented the changes in `comp-i396` branch. I've noticed that notification areas in panel, panel-compact, and popup are almost exactly the same. Does it worth separating it into a separate subcomponent?

**Comment by kirlat** [comment]
After Slack discussion with @balmas we decided to go ahead with splitting notifications into a separate subcomponent.

**Comment by kirlat** [comment]
I think that it's better to align a Log in/Log out button the same way we align a language switcher: to the right. They look much better together and, as an additional benefit, it saves vertical space:
![image](https://user-images.githubusercontent.com/18631055/56023530-1b9aa600-5d1f-11e9-9140-f5f637e7dc69.png)
Would it be OK to have it like that?

**Comment by balmas** [comment]
@kirlat I might have miscommunicated slightly on this ... the design firm suggested we use the tertiary button style, with just the outline for the notification, as in the attached screenshot. I think maybe you did this for the Login button rather than the notification text?

I.e. I think the notification text itself maybe should be white background with the outline , and then any buttons inside the notification should just be the regular corresponding button. Does that make sense?

**Comment by balmas** [comment]
to try to clarify further, they weren't suggesting that the notification itself be a button, but instead be outlined like the tertiary button. I don't know if works or not.

**Comment by kirlat** [comment]
Oh, sorry for misunderstanding! Yes, that makes sense. The only question I have is what would be a regular corresponding button in case of notifications: a primary or a tertiary one?

Also, how about important notifications? Should they be on white background as well, but be in alpheios-color-vivid and outlined with this color too? Should they have buttons of different color?

**Comment by balmas** [comment]
These are good questions. I feel like the button inside a notification should match the color of the notification. Do you agree?  So maybe we use the muted color for informational notifications and the vivid color for errors/warning notifications?

**Comment by kirlat** [comment]
Yes, it might be a good solution. Let me implement it and see how it will blend with the rest of the visual environment.

**Comment by kirlat** [comment]
I applied some of the suggested styles and this is how it looks with message boxes of the same size and shape as before (variant A):
![image](https://user-images.githubusercontent.com/18631055/56268814-5592f000-6103-11e9-9e2e-5c899169ec60.png)

My first impression was that it is rather bleak. By its nature, notification message should convey something important, it should display a message we want to be noticed by the user. In many scenarios we want user to react on that message; in some sense it is a user's call to action. I think it should be one of the most noticeable areas within a popup. It should attract attention. But when implemented like above, on my opinion, it is easy to miss, especially when user is not absolutely concentrated on examining the content of the popup (which, on my opinion, will happen often). 

Trying to make it stand out more, I've added margins around notification messages and rounded the borders so that each message would form a clearly visible box of its own. But I think it's still probably not enough, even though I like this better (variant B):
![image](https://user-images.githubusercontent.com/18631055/56269435-b3740780-6104-11e9-9516-8f50b4680be9.png)
 
Our current design is pretty colorful, and if we want messages to stand out we probably need something even bolder than that (variant C):
![image](https://user-images.githubusercontent.com/18631055/56269727-5fb5ee00-6105-11e9-9185-353e73bd30f2.png)
But that's pretty much a variation of what we had before, and I'm not sure if we should use it.

I think it's a pretty important piece of an overall UX and we should do all we can to make it work as expected (i.e. being noticed by users). What do you think would be our best course of action here?

**Comment by balmas** [comment]
I like the last option, and as we discussed maybe experimenting with opacity to make them a little less dense

**Comment by kirlat** [comment]
As discussed at Slack, I will implement a version with semi-transparent notifications with a thin border around them:
 
![image](https://user-images.githubusercontent.com/18631055/56300982-f3101300-6147-11e9-9668-c43002ac3d90.png)

**Comment by monzug** [comment]
build 1.0.0.17
![notification 2](https://user-images.githubusercontent.com/41396793/58371514-d356d200-7edf-11e9-93d7-b431b864a853.JPG)
