### ISSUE TITLE
add a component for browsing inflection tables

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#40]
We need a component which enables a user to browse and view inflection tables without first looking up a word.  Attached are screenshots of this from V1 of the Alpheios tools
![screenshot from 2018-05-03 09-09-03](https://user-images.githubusercontent.com/644870/39578282-bbad5e6c-4eb1-11e8-9a50-d183de307b7c.png)
![screenshot from 2018-05-03 09-08-43](https://user-images.githubusercontent.com/644870/39578283-bbc0afbc-4eb1-11e8-983c-9801ebae290a.png)

**Comment by balmas** [comment]
Based upon feedback from one of biggest current user bases in Brazil, I think we need to have at least minimal browsing capability for inflection tables in the next release. (It's a prerequisite to retiring their use of the V1 tools). Maybe we could do a first implementation without full navigation support - i.e. just to provide an ordered list of all the tables and the ability to get from the list to a table and back to the full list again.

**Comment by kirlat** [comment]
Please review a preliminary version of a component. It shows itself on top of inflection tables in a webextension panel. For it to appear, one has to click on either Greek or Latin word. A component for the corresponding language will be shown then above the "regular" inflection table.

It can be downloaded as https://github.com/alpheios-project/webextension/archive/comp-i40.zip.

During testing I was comparing this component's output with V1. However, a list of tables do differ sometimes as we do not have all tables from V1 (some Greek pronouns) or due to something else which I cannot identify at the moment. Would really appreciate any help here.

What is not working;
 - Does not have Latin irregular verbs yet
 - Does not have Greek noun simplified table. It gives some really strange error message, but I will pin it down.
- Some Greek pronouns are probably not fully correct (probably some columns are hidden).
 - You tell me :-)

I would really appreciate your feedback on its look and feel, in addition to table's correctness checks. This is a really important question in deciding to what components each piece of Vue.js presentational code should go and how much code can be shared between these table and the "regular" ones.

I tried to use a really minimal styling possible. However, I did apply some styles where, I think, it was necessary to visually separate different pieces of data. I was concentrating on presenting the information users would need most in the clearest way possible. I was also keeping mobile users in mind too.

I do have some questions about the components:
1. Would the current placement of the component be good for our users?
2. Would the presentation of information within a component as it is now satisfy our requirements?
3. Do table render fast enough? Currently it pre-renders all tables the moment inflection browser component is open. Would that be good or do we need to do it differently?
4. It uses the same title as we have for "regular" tables. Would we like to replace them with something else?
5. Do we want to show table in the same format as we show regular inflection tables (fonts, colors, sizes, etc.)?
6. Do we want to show linked tables below the main one? Right now it shows the main table only. I was thinking that too many tables under one collapsible title can be confusing, but if we need to show multiple tables there, we can do it.
7. Many tables are built using a "real" word as a source. That's why they have suffix/form matches highlighted. Does this make sense in an inflection browser? Do we need to show matches here at all?
8. What Latin irregular verbs do we need to show?
9. Do we need to have some inflection table groups collapsible? I think that would make inflection tables harder to find. Right now inflection tables are shown in a TOC style which I believe is the clearest. However, it may make sense to make some sections collapsible for long groups (but I still think it will be easier to scroll than to click to open a section, especially for mobile users).
10. Do we need to show a component even if user did not click any words to check yet (i.e. immediately after a component activation if default language is Latin or Greek)?

What suggestions and corrections do you have? Please share your feedback!

**Comment by balmas** [comment]
Q2. Would the presentation of information within a component as it is now satisfy our requirements?

I think I am fine with this for this release with one exception: I would like the top level of the selector to allow the user to choose between Latin and Greek, and then from there expand to the tables for that language.

**Comment by balmas** [comment]
Q3. Do table render fast enough? Currently it pre-renders all tables the moment inflection browser component is open. Would that be good or do we need to do it differently?

I think the speed is fine for now.

**Comment by balmas** [comment]
Q4. It uses the same title as we have for "regular" tables. Would we like to replace them with something else?
The titles that are there now are fine. But for the Latin Irregular Verbs, we will want the titles to be specific to the verb that is shown as in V1:
![verbs](https://user-images.githubusercontent.com/644870/45304516-42bd9a80-b4e6-11e8-820b-9ff3ca8f4053.png)

**Comment by balmas** [comment]
Q4. Do we want to show table in the same format as we show regular inflection tables (fonts, colors, sizes, etc.)?
YES

**Comment by balmas** [comment]
Q6: Do we want to show linked tables below the main one? 
I think the answer to this is NO for suffixes, and YES for full form tables.  I.e. so YES for Greek paradigms and Latin Irregular Verbs.

**Comment by balmas** [comment]
Q7. Many tables are built using a "real" word as a source. That's why they have suffix/form matches highlighted. Does this make sense in an inflection browser? Do we need to show matches here at all?
NO I do not want to show matches here.

**Comment by balmas** [comment]
Q8. What Latin irregular verbs do we need to show?
I would like to show tables for every distinct lemma in the data source. But I'd like to show them only under the verbs section, and not under the subtable sections.  
So, for example, the Participles and Supine browse options should just show the general tables for participles and supines. And there should be a separate section for irregular verbs that lists the lemma + principal parts of each irregular verb as the title of the tables, and then clicking on that should show the main irregular verb table for that verb, and  all of the linked tables for it.

**Comment by balmas** [comment]
Q9. Do we need to have some inflection table groups collapsible?
I think it's okay the way it is now. I might get overruled on that though. But I am okay with this until then.

**Comment by balmas** [comment]
Q10. Do we need to show a component even if user did not click any words to check yet (i.e. immediately after a component activation if default language is Latin or Greek)?
Yes, See my answer to Q1 and Q2 which addresses this.  I think we should always allow the user to browse the tables when the open the Inflection Tables panel, and that regardless of what the current or preferred language is, they be able browse either Latin or Greek tables.

**Comment by kirlat** [comment]
Need some clarifications on this requirement;

> When the Inflection Panel opens, if the Popup is not also open with results from a word lookup, then keep the component where it is, at the top of the panel.

>When the Inflection Panel opens, if the Popup IS ALSO open with results from a word lookup, then the component appears BELOW the tables that are specific to the popup, and at top we show a link to the inflection table browser, which scrolls the user to the location of the component at the bottom of the panel. (probably also with a "Top" link that brings the user back to the top of the panel)

Right now, when the panel is open and no lexical query has been made yet (i.e. as on webextension activation), according to previous requirements, and inflection icon is hidden (because there is no lookup related inflection data available). Because of this, there is no way to access an inflection browser.

Do we want to show an inflections icon if a default, or currently selected in options language is Latin or Greek (the one we have inflections for in a inflection browser)? Do we want to show an inflection browser always, no matter what currently selected language is?

I'm also thinking about other requirement to show selector in an inflection browser to choose between Latin and Greek and I'm wondering if we could tie it to a "Page language" option? When I'm trying to imagine a use case, I'm thinking about a person studying a single language. Let's say it's Greek. For that, person should probably go to options, set "Page language" to Greek (maybe we should change label to "Selected language" or something like that to reflect a purpose better), and then from now on it will treat page texts as Greek (as we expect person to probably read Greek texts only) and provide inflection browser tables for Greek. Probably the same person at the same moment of time won't need both Latin and Greek inflection tables in a browser, so do we really need to provide an extra switch there? I think users probably won't change between the two languages often. So maybe we can make users set language in global options once in a while, remember it, and provide language info for the one that is currently chosen? 
I just want to simplify UI as much as possible.
What do you think? Or would there be some other usage scenarios?

**Comment by balmas** [comment]
I'm going to answer that question in reverse order.  You are probably right that the primary use case is working with a single language at a time.  But there are use cases when the user is working with multiple languages, and our design this time around explicitly supports that. (An interesting one is the new Ge'ez  language feature, actually, because for this feature we have definitions provided in Latin...).

But that said, I do think there isn't a single right answer here. Probably eventually we need to overall improve the UI for the case when the user is working with multiple languages. We have already struggled with this on the lookup component (see #170). 

So I can live with tying the inflection browser to a single language at a time for now, but note that it's tricky to know which language to use in all circumstances. __current language isn't necessarily the same thing as page language__. Because the user could have the page language set to Latin and then do a lookup with the Language Override checkbox set to Greek.  If they are viewing results of a lookup in Greek, then the inflection browser should be for the Greek inflections, rather than Latin, even if the default page language is Latin. So, we may need to have this be dependent upon whether the user comes to the inflection tables from the popup or not (e.g., take the scenario where the the page language is latin, the user does a lookup entering a Greek word, then closes the popup. They open the panel and click on Inflection Tables. What language do we show? Probably Latin if it's the default language, although the last lookup was Greek...)

So this gets back to the first part of the question: "Right now, when the panel is open and no lexical query has been made yet (i.e. as on webextension activation), according to previous requirements, and inflection icon is hidden (because there is no lookup related inflection data available). Because of this, there is no way to access an inflection browser.

Do we want to show an inflections icon if a default, or currently selected in options language is Latin or Greek (the one we have inflections for in a inflection browser)? Do we want to show an inflection browser always, no matter what currently selected language is?"

I'm sorry about the changing requirements here, but now that we have inflection content that isn't tied to a lexical query, then yes I think we want to show the icon. Based upon what we did with the Grammar icon, hiding it we don't have a Grammar for the page language, we probably want to do the same for the Inflection icon, and only show it when the page language is one which has inflection tables. 

As I said above, I think the approach to making resources available for a multi-language use case needs some rethinking, but for now, we should be as consistent as possible about how we handle it throughout the app.

**Comment by kirlat** [comment]
Thanks for a detailed explanation! I understand know that it's more complex than I initially assessed. It would be very important to provide a convenient and logical UI for all use cases, but I'm afraid we probably don't have time right now to make it the best way possible.

So maybe, as a temporary solution, we can:
a. Always show an inflection tab icon, no matter what language is selected in a "Page language". Right now "Page language" is a way to set a language of a page, not of inflection tables in a browser. So we probably should not is it that way. Because of this, as we cannot determine the language (unless there is a lexical query), we should probably always show an inflection browser, and correspondingly, an inflection tables tab too.
b. We probably can show subsections for Latin and Greek tables collapsed with an option to expand them.
c. If there is a lexical query and we know a language, we can probably show a section of inflection browser for that language expanded: since it will be at the bottom of the panel (below query-related inflection tables) it will not obstruct the view.

What do you think? Does it make sense?

**Comment by balmas** [comment]
yes I'm fine with that.

**Comment by kirlat** [comment]
I fixed issues with Greek noun simplified table and with Greek pronoun tables (the ones that we have implemented). I also added Latin irregular verb tables. Inflection browser component has been moved to the bottom of the inflections panel. It now shows even if there is no inflection data from a lexical query available.

Inflection tables icon is now visible all the time as an inflection panel contains an inflection browser and we want users to be able to access it, even if there is no lexical query has been made yet.

Build link is https://github.com/alpheios-project/webextension/archive/comp-i40.zip.

We probably need to decide on what features from this issue are absolutely critical for the release and implement them first. Overall, there are many things involved into this (as it involves practically all the tables for two languages), and implementing everything might take time. For example, showing other tables below the main one will require redoing an inflections Vue component and that will involve retesting all inflection browser's tables and all regular tables as well.

**Comment by balmas** [comment]
I would like @monzug to test this and provide her feedback on what is absolutely required for the release. I think I could be okay with it as it is if new bugs aren't found.

Just for clarity's sake, here are the additional things I asked for above that aren't implemented yet and which I believe can wait:

1. addition of irregular participle, supine etc. below the irregular verb tables in the browser
2. addition of participles below the greek paradigm tables in the browser

**Comment by kirlat** [comment]
I added Greek paradigm participles, so I believe they are already there.

**Comment by balmas** [comment]
Right, I just meant displaying them directly below the related main paradigm, in addition to separately in the browser.

**Comment by kirlat** [comment]
Oh, did not get that, thanks for clarifying!

**Comment by monzug** [comment]
going  back to Q10, it works smoothly like this: activate webextension, info panel is generated and I can select the Inflection icon, the message "Inflection data not available" is generated and below  user has the ability to browse Greek inflection tables and Latin inflection tables.

Maybe the message on top of browser is not longer necessary or may be it is. see below:

![no inflection data](https://user-images.githubusercontent.com/41396793/45587279-d53cb000-b8d1-11e8-9717-111c3cac3924.JPG)

**Comment by monzug** [comment]
Missing tables from the browser:
1) Greek possessive pronoun table are missing from browser and from tables (e.g. ἐμὸς, ἐμή, ἡμέτερα) - could the reason be that in morphology possessive and pronoun adj are combined?
2) Latin regular verb table are missing from browser. e.g. lookup for pulcher, the adj table is open,  I can't browse to regular verb tables. it's possible that I just could not find a way to do it.

**Comment by monzug** [comment]
stickiness.
when closing the inflection panel, the browser should refresh, right now it's sticky to last viewed table.
Open the noun inflected table (e.g. for word πόντῳ), close table, then lookup a greek pronoun, e.g. μοι, and click to Inflect. the Personal pronoun table is open but also the noun inflection table is still open in the browser with the matches highlighted. I think we should close the noun table.

**Comment by monzug** [comment]
Pronoun table and drop-down navigation:
from lookup enter  αὐτόν   and click to Inflect. The pronoun inflection table  is generated but  I was expecting the Intensive pronoun table.
1) why did I get the Pronoun table and not the Intensive table?
2) why the Pronoun table is not listed in the browsing section of the pronoun?
3) there is not exact match here, why?
More about the drop-down on the right side of the Pronoun table. It has 4 type of pronoun, while the browsing pronoun table have 9 different tables. 
4) what's the drop down for? 
5) why is it populated by only 4 pronoun tables: pronoun declension, reflexive pronoun declension, personal pronoun declension, demonstrative pronoun declension?

**Comment by monzug** [comment]
question:
let's look at Greek verb "ἔννεπε" ( ἐννεπ - ε ). it does show the ω-Verbs: Present System Active
with the infinitive βουλεύειν and the participle βουλεύων, βουλεύουσᾰ, βουλεῦον
If I browse to the Regular ω Verbs and expand the ω-Verbs: Present System Active
I do have the main table but the Infinitive is missing.
The participle can be found under Participles, then expanding Participles in -ων, -ουσα, -ον (present and future active, uncontracted)
Is there a plan to add the infinitive in a separate section? or should we keep the infinitive attached to the main table?

**Comment by monzug** [comment]
last but not least, I haven't checked the content of tables (I did for some) as requested by @kirlat. this is in my to do list.

**Comment by kirlat** [comment]
@monzug, thanks for testing it! Below are some of my comments:
1. I'm fine with removing "Inflection data is unavailable message" when inflection browser is present. @balmas, what do you think?
2. It seems that Greek possessive pronouns inflection table is not implemented yet, and that's because we don't have possessive pronouns data in our Greek CSV file. I don't remember exactly why is that. Probably there were some difficulties with this data, but I really can't say. I can work to fix that. @balmas, how critical is it for us to have it right now?
3. "Latin regular verb table are missing from browser. e.g. lookup for pulcher, the adj table is open, I can't browse to regular verb tables." - do I understand correctly that this is related to inflection table browser not showing those tables? As I understnad, pulcher is an adjective and we should show just an adjective table for it. We have the following tables for regular Latin verbs (I name them for grouping features as I don't know any better way): "conjugation-mood-voice", "conjugation-voice-mood", "mood-conjugation-voice", "mood-voice-conjugationt", "voice-conjugation-mood", and "voice-mood-conjugation". I can include those tables into an inflection browser. In what order should they go? What title should they have?
4. "Stickiness: when closing the inflection panel, the browser should refresh, right now it's sticky to last viewed table." - agree that on a new lexical query we should collapse previously open tables in an inflection browser. @balmas, are you OK with that?

**Comment by kirlat** [comment]
> Pronoun table and drop-down navigation:
> from lookup enter αὐτόν and click to Inflect. The pronoun inflection table is generated but I was expecting the Intensive pronoun table.
> 
>     1. why did I get the Pronoun table and not the Intensive table?
> 
>     2. why the Pronoun table is not listed in the browsing section of the pronoun?
> 
>     3. there is not exact match here, why? also for "ὅστις " , I do not have an exact match.
> 
> 
> More about the drop-down on the right side of the Pronoun table. It has 4 type of pronoun, while the browsing pronoun table have 9 different tables.
> 4) what's the drop down for?
> 5) why is it populated by only 4 pronoun tables: pronoun declension, reflexive pronoun declension, personal pronoun declension, demonstrative pronoun declension?

There are two independent components here: 
- an inflection view at the top of the panel that shows tables for the result of a current lexical query.
- an inflection browser at the bottom that shows a list of "standard forms" of inflection tables.
Those two components are not interacting with each other currently and should be considered separately. This issue is related to the inflection browser. If there is a problem with incorrect inflection tables shown for a lexical query, then this should probably be a separate issue. @balmas, what do you think?

Drop down on the right side of the pronoun table shows four tables that the library thinks are relevant to the current lexical query. The drop down is used to switch between those four tables within a "current lexical query results" component. 

In inflection browser is a separate component. It shows nine tables because those are all pronoun tables it knows about. It has nothing to do with results of the lexical query. I was taking a list of tables from V1, except those that are not implemented currently.

I'll check this lexical query and figure out why does it show exactly those four tables and why it does not have proper matches sometimes.

**Comment by kirlat** [comment]
> let's look at Greek verb "ἔννεπε" ( ἐννεπ - ε ). it does show the ω-Verbs: Present System Active
> with the infinitive βουλεύειν and the participle βουλεύων, βουλεύουσᾰ, βουλεῦον
> If I browse to the Regular ω Verbs and expand the ω-Verbs: Present System Active
> I do have the main table but the Infinitive is missing.
> The participle can be found under Participles, then expanding Participles in -ων, -ουσα, -ον (present and future active, uncontracted)
> Is there a plan to add the infinitive in a separate section? or should we keep the infinitive attached to the main table?

I was discussing this with @balmas, and the reason for us not showing related tables for "ω-Verbs: Present System Active" and some other tables too is a technical limitation in the inflection browser. It can show only one table per section (i.e. collapsible title) now.

This is related to the current structure of inflection table components. Implementing this feature would require a change in that structure. This is not very hard per se, but because this change will affect display functions for all inflection tables, it will require retesting all inflection tables for lexical queries and for inflection browser. That will take a lot of time and effort.

We decided to postpone this to after release, where we'll do other change to the UI components (aka refactoring). It would make sense to make all UI changes that are related at once and then retest them all together. @monzug, @balmas, what do you think? How critical is that?

**Comment by kirlat** [comment]
> forgot to mention, supine table has the old style with the 4th conjugations. One thing is missing: the regular verb table under the Supine. lookup for monitu, I can see the Supine but I do not have a way to go to regular table.

I think this is related not to the inflection browser, but to "regular, lexial-query-initiated" inflection tables. @balmas, shall I create a separate issue for that?

**Comment by balmas** [comment]
> @monzug, thanks for testing it! Below are some of my comments:
> 
> 1. I'm fine with removing "Inflection data is unavailable message" when inflection browser is present. @balmas, what do you think?

Agree

**Comment by balmas** [comment]
> 3. "Latin regular verb table are missing from browser. e.g. lookup for pulcher, the adj table is open, I can't browse to regular verb tables." - do I understand correctly that this is related to inflection table browser not showing those tables? As I understnad, pulcher is an adjective and we should show just an adjective table for it. We have the following tables for regular Latin verbs (I name them for grouping features as I don't know any better way): "conjugation-mood-voice", "conjugation-voice-mood", "mood-conjugation-voice", "mood-voice-conjugationt", "voice-conjugation-mood", and "voice-mood-conjugation". I can include those tables into an inflection browser. In what order should they go? What title should they have?

We should have a single "Regular Verbs" entry in the browser, and this should bring up these 4 views, switchable in the dropdown (e.g. it brings up the "conjugation-voice-mood" permutation, with all 4 available in the dropdown.) 

If this is going to be difficult, then there should be 4 entries in the browser, one for each permutation, titled Regular Verb (conjugation-voice-mood), etc.

**Comment by balmas** [comment]
> 2. It seems that Greek possessive pronouns inflection table is not implemented yet, and that's because we don't have possessive pronouns data in our Greek CSV file. I don't remember exactly why is that. Probably there were some difficulties with this data, but I really can't say. I can work to fix that. @balmas, how critical is it for us to have it right now?

Looking back at my notes from earlier this year, I think this was probably both intentional and an oversight. We had in V1 4 possessive pronoun tables, one which tried to combine them all, and then 1 each for first, second and third person. We decided to drop the one which tried to show all 3, but we should have kept the individual first, second, third person tables.   I am going to enter a separate issue for this. Will have to decide if we want it to delay the release or not.

**Comment by balmas** [comment]
> 4. "Stickiness: when closing the inflection panel, the browser should refresh, right now it's sticky to last viewed table." - agree that on a new lexical query we should collapse previously open tables in an inflection browser. @balmas, are you OK with that?

Yes, this is fine with me.

**Comment by balmas** [comment]
>   Those two components are not interacting with each other currently and should be considered separately. This issue is related to the inflection browser. If there is a problem with incorrect inflection tables shown for a lexical query, then this should probably be a separate issue. @balmas, what do you think?
Yes, as discussed in our check-in today, keeping the concerns separate is important, but also this may highlight an issue with our implementation because it seems likely that it won't be obvious to the user that the browser is offering a different set of tables than the query results, or the rationale for this. @monzug Kirill suggested that perhaps when we have results from a lexical query in the inflection tab along with the browser, using the browser should collapse the tables that are tied to the query results. I think this is a good at least short term approach to trying to reduce confusion. do you agree?

**Comment by balmas** [comment]
> > forgot to mention, supine table has the old style with the 4th conjugations. 

> I think this is related not to the inflection browser, but to "regular, lexial-query-initiated" inflection tables. @balmas, shall I create a separate issue for that?

I think this is because the fix to the Supine table hasn't been merged into the comp-i40 branch yet.

**Comment by balmas** [comment]
> > this is something for which I do not have a reproducible scenario but it's worth to mention. From my note:
> > if I collapse all tables and then lookup again the word, it does not open the related table but just the navigation.
> 
> I was copying behavior from V1 where it was just showing a list of tables. We might pass lexical query data to the inflection browser so the corresponding inflection tables be open, but I'm not sure we need that because we'll already have those relevant inflection tables open at the top "lexical query results" component. @balmas, what would be the best way to present data to the user who makes a lexical query and then starts to browse inflection tables? What would suit best to her or his needs?

I'm not sure what the right answer here is, and think it's something we could solicit feedback on from users.   My personal preference for the release would be to prioritize the tables that are most relevant to the lexical query and as long as the user can use the browser to get to other tables they are interested in, if the browser doesn't retain state that is okay with me.

**Comment by balmas** [comment]
> > let's look at Greek verb "ἔννεπε" ( ἐννεπ - ε ). it does show the ω-Verbs: Present System Active
> > with the infinitive βουλεύειν and the participle βουλεύων, βουλεύουσᾰ, βουλεῦον
> > If I browse to the Regular ω Verbs and expand the ω-Verbs: Present System Active
> > I do have the main table but the Infinitive is missing.
> > The participle can be found under Participles, then expanding Participles in -ων, -ουσα, -ον (present and future active, uncontracted)
> > Is there a plan to add the infinitive in a separate section? or should we keep the infinitive attached to the main table?
> 
> I was discussing this with @balmas, and the reason for us not showing related tables for "ω-Verbs: Present System Active" and some other tables too is a technical limitation in the inflection browser. It can show only one table per section (i.e. collapsible title) now.
> 
> This is related to the current structure of inflection table components. Implementing this feature would require a change in that structure. This is not very hard per se, but because this change will affect display functions for all inflection tables, it will require retesting all inflection tables for lexical queries and for inflection browser. That will take a lot of time and effort.
> 
> We decided to postpone this to after release, where we'll do other change to the UI components (aka refactoring). It would make sense to make all UI changes that are related at once and then retest them all together. @monzug, @balmas, what do you think? How critical is that?

I think I still want to let this one go for now.

**Comment by kirlat** [comment]
> We should have a single "Regular Verbs" entry in the browser, and this should bring up these 4 views, switchable in the dropdown (e.g. it brings up the "conjugation-voice-mood" permutation, with all 4 available in the dropdown.)
> 
> If this is going to be difficult, then there should be 4 entries in the browser, one for each permutation, titled Regular Verb (conjugation-voice-mood), etc.

I think a drop-down would be problematic without changing too much in an inflection component. So it would be great if we could postpone this for later. I can just list all those tables under the "Regular Verbs" entry for now.

**Comment by balmas** [comment]
So, because this is a long chain, just recapping all the specific changes that are requested following this round of testing:

- [ ] remove the "inflection data is unavailable" when the browser is present
- [ ] add all 4 variations of the regular latin verb tables in the browser, grouped under a "Regular Verbs" entry
- [ ] on a new lexical query we should collapse previously open tables in an inflection browser.
- [ ] When we have results from a lexical query in the inflection tab along with the browser, using the browser should collapse the tables that are tied to the query results (but we may want to revert this if it is buggy)

The greek pronoun issue has been moved to #213 

I think that's it. Hope I didn't miss anything!

**Comment by kirlat** [comment]
Implemented all four features listed in the comment above, please review.

**Comment by balmas** [comment]
these changes seem to be working as expected. Please go ahead and submit the PR. Any remaining issues will be submitted as new issues to be resolved post-merge. Thanks!

**Comment by kirlat** [comment]
Great! Submitted corresponding PRs.

**Comment by monzug** [comment]
questions:
- remove the "inflection data is unavailable" when the browser is present
that's done. is it ok that we display the Latin browser expanded (list of all latin inflection tables) if we had it open in previous lookup? or should it be always collapsed?
-  add all 4 variations of the regular latin verb tables in the browser, grouped under a "Regular Verbs" entry
that's done. also, supine, participles, infinitive, imperative are under this section which is share with the irregular verb. is it ok?
- When we have results from a lexical query in the inflection tab along with the browser, using the browser should collapse the tables that are tied to the query results
this does not work for Greek verbs.  They are missing the option to close or  to open table [+] or [-] when browsing other tables.

**Comment by balmas** [comment]
@kirlat 
Can you fix these two easily?
-  [ ] Always collapse both the Latin and Greek inflection browsers when the panel is closed. 
-  [ ] For the Greek Verbs add the missing the option to close or to open table [+] or [-] when browsing other tables

I will also add a little more hierarchy to the Latin verb listing.

**Comment by kirlat** [comment]
Sure, should be no problem. Just need some clarifications;
> Always collapse both the Latin and Greek inflection browsers when the panel is closed.
Right now it opens a language tree (Latin or Greek) for the language of the current, or the latest lexical query. Should we now change it to always showing (when panel is open) Latin or Greek trees collapsed? 
> For the Greek Verbs add the missing the option to close or to open table [+] or [-] when browsing other tables
I think we don't have Greek Verbs there right now (if I'm getting this requirement right which I'm not 100% sure of). Can you please provide more information on this one? Thanks!

**Comment by balmas** [comment]
I will look at this one some more to be sure I understand what @monzug is asking for.

**Comment by balmas** [comment]
ok @monzug 

re 

>remove the "inflection data is unavailable" when the browser is present
that's done. is it ok that we display the Latin browser expanded (list of all latin inflection tables) if we had it open in previous lookup? or should it be always collapsed?

@kirlat points out that this is by design - when you look up a Latin word, the Latin browser will be open and when you look up a Greek word, the Greek browser will be open. I think that is sensible so would like to leave it as is. 

There are 2 fixes though in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-12/dist 

re 
>add all 4 variations of the regular latin verb tables in the browser, grouped under a "Regular Verbs" entry that's done. also, supine, participles, infinitive, imperative are under this section which is share with the irregular verb. is it ok?

I have made a subheadings - "Sort by..." for the variations on the regular tables and then "Other forms" for the rest of the regular tables. Does it make sense?

and re
>When we have results from a lexical query in the inflection tab along with the browser, using the browser should collapse the tables that are tied to the query results
this does not work for Greek verbs. They are missing the option to close or to open table [+] or [-] when browsing other tables.

I have added collapse/expand to the Greek verb paradigms.

**Comment by monzug** [comment]
I do not see the latest two fixes in the build 12.

**Comment by balmas** [comment]
oh darn, my mistake :-( 

They are there now in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-13/dist as well as the last change for alpheios-project/inflection-tables#170 (the change to show the panel before the inflection browser is fully loaded)

**Comment by monzug** [comment]
tested in build 13. there is two minor glitches in the greek verb browser. 
1) we do have now the option to close the verb table on top. However when I open an other Greek verb table from browser, on top the infinitive and participle tables shows up again. if I expand, it goes back to the regular full table if I collapse it goes to the infinitive/participle tables
e.g. lookup for ἔγνω, the γιγνώσκω: Aorist System Active table is generated, then open in the browser Perfect System Middle-Passive: indicative, infinitive, participle table and then close it. on top  the infinitive and participle tables Aorist System Active table is collapsed, if I expand it, it goes to the actice table again without the infinitive/participles
2) when I close the verb table and lookup again for same word and click on Inflect, the inflection table is generated in collapsed state.

**Comment by balmas** [comment]
this can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-14/dist

**Comment by monzug** [comment]
1) has been fixed
2) does still occur but it's ok. user does have the option to expand it.
