### ISSUE TITLE
Overloaded CPU because of progress bar

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#407]
@balmas and @kirlat ,
I have commented  getting all data from sources, turned off inflections, wordUsage, wordlist and etc.
So the result of any word select will be like this:

![image](https://user-images.githubusercontent.com/12377640/55846582-8b772800-5b89-11e9-8ac6-df7a539f53c9.png)

Saved this state of the components to this branch - https://github.com/alpheios-project/components/tree/testing-performance-progress

**Comment by irina060981** [comment]
I have tested with Chrome and Firefox.
The problem with progress bar animation is specific for Firefox, in Chrome I didn't detect the overload.

Here are video tests:

**Comment by kirlat** [comment]
Investigating the issue and looking for a solution I found a great Smashing Mag's article about rendering optimizations: https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/.

Following the guidance, I removed animations of width and background color (that one was not needed) and emulated width change with a `transform`. This allowed to offload animation rendering from CPU to GPU by forcing browser into creating two compositing layers (one for the animated bar and another one for the text that is placed above it).

As a result, a CPU usage on my machine went down 5x to 10x times to 1-1.5% and the GPU load is reported as being 0 (probably because it's too small to repored). I was testing in FF 67b10 on Win10, on Core i7-4800MQ. It can be different on other platforms, but I hope it will still show significant improvements similar to what I've experienced.

Will submit a PR to make it available for further testing and verification.

**Comment by balmas** [comment]
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment]
yes, I could see an improvement. Now for words like adquiescat and ludere and incitare (from https://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0472.phi001.perseus-lat2/passage/1.1-1.10) CPU goes up to 30% but no more. before this fix, CPU usage could go up to 50%
