### ISSUE TITLE
Multiple users: need to reload to see user's wordlist

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#432]
Have two users each with its own wordlist. when I logged out from User A and login as User B, the wordlist displayed is the one from User A. I need to reload the page and login again. note that I am not prompt for authentication but I get automatically in as User B. Now User B's wordlist is correctly generated.

**Comment by irina060981** [comment]
I tried to check this bug in Chrome - but I failed to do it with Googles accounts, because if I was logged in with one account - I couldn't choose another Google account - it is not suggested and immediately log me in with previous credentials.

I even don't need to choose an account and enter a password.
So bif it would be used on a computer with multipe users - it could be a problem.

**Comment by irina060981** [comment]
I have created additional account (not google) and tried to reproduced the bug in the last branch from the PR - https://github.com/alpheios-project/components/pull/438
I wasn't able to reproduce.
May be this bug was because of cached wordlist in reactive properties. (https://github.com/alpheios-project/components/issues/434)
Should be checked again, I believe

**Comment by balmas** [comment]
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by balmas** [comment]
@monzug you can test this with the build at https://github.com/alpheios-project/webextension/tree/qa-3.0.0.27/dist (sorry no Safari build yet)

**Comment by monzug** [comment]
uhm, this still does not work in 3.0.0.28. I have two users and they basically share one wordlist. each user should have its own wordlist.

**Comment by balmas** [comment]
Hmm. I can't reproduce this myself. I tried several login/logout switching users and each time the wordlist gets properly updated.  @monzug I feel I must be missing something. Can you give me your account ids so that I can look at the data in the service?

**Comment by monzug** [comment]
I tested with the following ids: Test@test.it  and prova@prova.it
I did also delete the existing wordlist and started from scratch.

**Comment by monzug** [comment]
Confirm that I am still able to reproduce the shared wordlist. After deleting all the words in one wordlist, the two users started sharing the wordlist. will start from scratch with two new users to verify if it's related to deleting all words.

**Comment by monzug** [comment]
I confirm that I do experience that some words are shared among wordslists. I thought these could be the look-up words before login but I have seen it also with lookup words added to wordlist after login.
I did create two users: user a  and user b each with 3 lookup words from different section of same book. the words were lookup before login and then added to the wordlist. then I logout/login few time switching users and adding new words each time.  the new lookup words are added to both wordslist.
Pls let me know if you want a step by step scenario with screenshot.

**Comment by balmas** [comment]
ok, this is very helpful. I am guessing something is not getting cleared on logout. I will investigate. Thank you!

**Comment by monzug** [comment]
see screenshots of usera and userb wordlists
![userb-wordlist](https://user-images.githubusercontent.com/41396793/56426906-eb578800-6287-11e9-87ac-315747131f7a.JPG)
![usera-wordlist](https://user-images.githubusercontent.com/41396793/56426907-ebf01e80-6287-11e9-863f-9fdb4bd44f58.JPG)

**Comment by balmas** [comment]
yes, I have been able to reproduce now. Thank you!

**Comment by balmas** [comment]
there's something going seriously wrong with the queuing of update requests -- the more lookups you do the more requests get queued. (@monzug as KT used to say ... "a smoking gun") continuing to investigate.

**Comment by monzug** [comment]
So many memories....

**Comment by balmas** [comment]
I think I have found the problem here.  

In the UserDataManager constructor, we subscribe to a set of WORDITEM events, binding the current instance of the UserDataManager to the subscription

Whenever we authenticate as a new user, we create a new UserDataManager with the new authentication data. Even though we set the reference to the prior UserDataManager pointed at by the UIController to null when we logout, the old instance is hanging around, because it is held in the subscribers array for the Events. 

So, the problem compounds itself the more times we login and logout with multiple users.

@kirlat I think we need a way to unsubscribe events.  We don't currently hold a reference to the subscription when we create it, so I don't think we have an easy way to unsubscribe right now.  What do you think? Maybe the Event.sub event should return the subscription so that any object that subscribes can clean up after itself by removing it?

**Comment by kirlat** [comment]
@balmas I've modified a an event so that a `sub(...)` will return a function that, when called, will unsubscribe the current subscriber from an event. Please see https://github.com/alpheios-project/data-models/blob/issue-comp-432/tests/ps-events/ps-event.test.js#L47-L55 for an example

I've also added an `unsubAll()` method that will unsubscribe all subscribers from an event.

Please let me know if this is enough to achieve what we need. In that case I can submit a PR with the changes. Thanks!

**Comment by balmas** [comment]
@kirlat I think that should work

**Comment by kirlat** [comment]
Submitted a PR with the change
