### ISSUE TITLE
Status message icon in the overlay

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#443]
Status message icon in the overlay is for testing, correct?

_Originally posted by @monzug in https://github.com/alpheios-project/components/issues/389#issuecomment-483309492_

Need to make sure the mechanism for not showing status messages is working

**Comment by balmas** [comment]
@kirlat can you double check this? Monica says that the status icon was there in the last build. I can't remember what the switch is for this.

**Comment by kirlat** [comment]
The visibility of a status tab icon is determined by the Log level setting. In order this icon to appear the value must be set to "Verbose" (the other setting is "Normal").

There was a problem in the business logic of showing this icon and I've fixed that. 

I think it makes no sense to show this icon if log level is normal because it is not the subject to flashing. So it should be hidden if the log level is "normal" and visible if the log level is "verbose". Would it be a good approach?

**Comment by balmas** [comment]
yes that makes sense.

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
Not longer visible. Thanks
