### ISSUE TITLE
remove word-specific icons from the overlay nav

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#457]
as @abrasax and I reviewed this design today, we realized that a simple solution to both the problem in #456 and the display of the overlay toolbar on a low resolution would be to remove the icons that duplicate functionality that is available via buttons on the popup from the overlay nav.

The definitions, inflections, examples and diagram icons only ever are useful when you have the results of a current word lookup, in which case they are all available from the popup.  And now that we close the overlay nav when the panel nav is open, there is no need for all of the features on the panel nav to be in the overlay nav toolbar.

So we would like to remove  definitions, inflections, examples and diagram icons from the overlay toolbar entirely.

**Comment by kirlat** [comment]
Do I understand correctly that the problem is with the row of buttons being too tall and not fitting fully into the viewport height on small resolutions? Then I think removing buttons as suggested above is a good solution for now.

But I think it will be good to try to avoid a UI fragmentation depending on the device type (mobile/desktop), resolution, etc. It will increase UI complexity, maintenance costs, and may cause more confusion to the user. I am also keeping in mind a lookup component that we have to place somewhere on mobile.

So I'm thinking what if we, in the future updates, create some kind of an "action panel": something that will hold all actions available to the user and at the same time compact enough to be shown on devices will limited screen estate (mobile) yet something that would make sense on desktops? Maybe something similar by spirit to the "Getting started" panel as shown in https://github.com/alpheios-project/design-guidelines/blob/master/v3/AlpheiosReader-Mobile/Reader/Getting-Started.png?

It is wider than the current column of buttons of a toolbar, and because of that we can place icons in both rows and columns inside it. This will reduce an overall height of this element. It is also big enough to fit a lookup component too. And it is flexible to hold any kind of information. We can easily make its content context dependent.

We can attach such panel to several actions:
1. User clicks on the floating toolbar's main button.
2. User clicks on the menu button on a mobile panel (it can replace a mobile menu).
3. If we will have trouble fitting too many buttons into the limited width of the panel's header (as we starting to have now, with bigger buttons), we can show only most recently used there (we can make it configurable by the user so that he/she will choose which ones be shown) and add a menu-like button to the header that will call an action panel. An action panel with thus provide access to the rest of the available functionality.
4. Maybe show action panel via a right click menu.

It can also fit into an AlpheiosReader well too, I think. We can attach a display of such panel to the click on the "Open Tools" area:
![image](https://user-images.githubusercontent.com/18631055/56409854-ebf21d80-628b-11e9-97cd-a3916c4a3963.png)

As a result, we could have a simple, flexible, and universal actions UI that will be the same for all types of Alpheios applications on all devices. Users familiar with one app type will have no difficulty in switching to the other. It will also convey an Alpheios brand and UI style across the apps which is a good thing too.

What do you think about this idea in general?

**Comment by balmas** [comment]
> Do I understand correctly that the problem is with the row of buttons being too tall and not fitting fully into the viewport height on small resolutions? Then I think removing buttons as suggested above is a good solution for now.

That was the initial problem that @abrasax and I were discussing, but as we were exploring different alternatives, and feeling unhappy about the idea of having different versions of this toolbar on different devices/resolutions, it occurred to us that we don't actually *want* the word-specific actions on this toolbar, because they are redundant with the buttons on the popup and would only be used when there is actually a popup present.

**Comment by balmas** [comment]
> But I think it will be good to try to avoid a UI fragmentation depending on the device type (mobile/desktop), resolution, etc. It will increase UI complexity, maintenance costs, and may cause more confusion to the user. I am also keeping in mind a lookup component that we have to place somewhere on mobile.

Yes, agree that we want to minimize the differences across devices as much as possible. That said, there will be some valid cases where we want different UI elements for mobile and desktop.  But these should ideally be cases where the user interaction paradigm is different, and not driven by screen real estate differences.

**Comment by balmas** [comment]
I am having a little trouble envisioning what you are suggesting with the action panel, but it sounds a bit like the direction @abrasax was thinking we might go with the toolbar so it might be worth doing a mockup. I am hesitant to increase scope right now but also don't want to shut the door on good ideas.

**Comment by kirlat** [comment]
> I am having a little trouble envisioning what you are suggesting with the action panel, but it sounds a bit like the direction @abrasax was thinking we might go with the toolbar so it might be worth doing a mockup.

I will try to make a wireframe to illustrate the idea.

**Comment by balmas** [comment]
Can be tested in 3.0.0.29 https://github.com/alpheios-project/webextension/tree/qa-3.0.0.29/dist and in Dropbox for Safari

**Comment by monzug** [comment]
Yes, I noticed the missing icons in build 3.0.0.29 chrome and firefox. I do not think the test environment has been updated to latest build as diagrams, examples etc. icons are still there.
![overlay-not-updated](https://user-images.githubusercontent.com/41396793/56741920-c2306f00-6741-11e9-9e93-ad0c146a3fcd.JPG)

**Comment by balmas** [comment]
texts environment is updated now

**Comment by monzug** [comment]
Thanks
