### ISSUE TITLE
Missing close button from text environment 

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#496]
tested in Chrome and Firefox in text env 1.0.0.7
missing the close button for the language message in the morphology pop-up in text environment
see screenshots
![close-bottom-missing-text-env](https://user-images.githubusercontent.com/41396793/57087041-3aaca800-6ccd-11e9-93ae-60152f91ba4e.JPG)
![close-button-alpheios-tools](https://user-images.githubusercontent.com/41396793/57087042-3aaca800-6ccd-11e9-8658-7363faf88458.JPG)

**Comment by balmas** [comment]
is this also the cause for the difference in the credits show/hide link which isn't working in the texts environment either?

**Comment by kirlat** [comment]
I found myself using `border-box` much more than `content-box`. I think the former is more intuitive: you set the size of the box itself, not the size of the content keeping in mind that the size of the box will be content size + paddings + border widths. I think that's the reason why Bootstrap overrode it for all elements in their rules (but not for *:before and *:after, even though it would be good for consistency, I think).

The problem with `box-sizing`, though, is that it is not inherited. Because of this, if the selector for which it is defined do not target the current element directly, `box-sizing` rule will not be applied. If we define the `box-sizing` rule for `.alpheios-content`, it will be applied to `.alpheios-content` only.

In Bootstrap it is defined for `*`, so it targets each element of the page directly. We cannot do that because this will leak our rules into host pages. I think we don't want that.

So our only option is probably to be as explicit in our CSS rules as possible and not to rely on anything.

I've updated the icon by setting the size of the SVG element directly. I've also fixed the link color that was overriden by the Bootstrap's styles.

**Comment by monzug** [comment]
not a big deal but the X button is a little off on my mac (also on the invitation to login)
see screenshot
![Screen Shot 2019-05-12 at 6 26 34 PM](https://user-images.githubusercontent.com/41396793/57585122-b539ac80-74b1-11e9-9cac-450894a06fc8.png)

**Comment by balmas** [comment]
in 3.0.0.34/1.0.0.12

**Comment by kirlat** [comment]
> not a big deal but the X button is a little off on my mac (also on the invitation to login)
> see screenshot

Is it in Safari on Mac? Strange thing is that I cannot reproduce it. Here is how it looks in my case:
![image](https://user-images.githubusercontent.com/18631055/57625746-8ac91b80-75a5-11e9-9c2f-8d1fd7582ec7.png)

**Comment by monzug** [comment]
looks good in 1.0.0.12. verified
