### ISSUE TITLE
make icon order consistent in mobile and desktop

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#504]
From @monzug 

mobile only: the order of the icons in lookup is different from panel.
panel: ...options, user info, wordlist
lookup: ...wordlist, user info, options

**Comment by kirlat** [comment]
@balmas, which icon order will it be better to use? I've changed the order so that most frequently used icons be located at the beginning of the list and least frequently used - at the end of it. I think this is consistent with generally accepted UI principles and established practices. For example, MS Office has most frequently used buttons (font size, color, etc.) at the left of their ribbon.

So in the lookup I've located the icons in the order of how often will they be used, to the best of my understanding.

What would be the best order for us?

**Comment by balmas** [comment]
I like: wordlist, user info , options

**Comment by kirlat** [comment]
Great, just submitted a PR

**Comment by balmas** [comment]
this is in embed-lib 1.0.0.10

**Comment by balmas** [comment]
actually I don't think this made it into the last embed-lib build. Will be in the next.

**Comment by monzug** [comment]
verified in 1.0.0.11 mobile and desktop
