### ISSUE TITLE
add ability to specify current language upon activation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#509]
when Alpheios is embedded in a page we need a way to specify the current language upon activation. Although we can already specify language on sections which are activated for lookups, we should also be able to specify the overall default for the page.

(So, for example, on the Alpheios reader, if we are looking at a collection of Greek works, the current language can be set as Greek for the lookup from the toolbar)

**Comment by kirlat** [comment]
@balmas: We have a `preferredLanguage` prop that allows to specify the default value of the current text's language via the UI. If we set it to the value that is provided during the Alpheios activation, this will allow us to solve the issue without adding too much complexity. The only side effect would be that if the preferred language is shown in the options page, its options value will be changed not by the user's will, but by the will of Alpheios embed lib integrators. Would such solution work for us? Or do we need another prop to store the language preference set during the embed-lib activation? What do you think?

**Comment by balmas** [comment]
hmm. Actually I wonder if we even want to expose that setting to the user when using the embedded library. I don't think we do. 

And we wouldn't want changes to it made by the embed-lib to impact what is stored to user preferences for the webextension.

So we might need a separate solution here.

**Comment by kirlat** [comment]
Then I think it's best to create a separate setting for it then. Language settings should probably have the following priority (top items are with a higher priority):
1. A language specified for the selected word;
2. A language specified for parent HTML elements of the selected word;
3. A language set by the embedded library during initialization (a subject of this issue);
4. A language set in user preferences (preferredLanguage) (will not be exposed for embedded lib users?)
Does the above sounds right?

**Comment by balmas** [comment]
yes I think so.

Just FYI, I will probably submit a PR today with the changes for #522  so you might want to wait to do this until then.

**Comment by kirlat** [comment]
Thanks for letting me know, I will work on #608 so far.

**Comment by kirlat** [comment]
I have a preliminary implementation of this working. However, during testing I discovered that there are many different scenarios of how language information is used in a system. To avoid possible confusion or misunderstanding I decided to put the summary of those rules here. It may also serve as a guideline for testing.

Current language is a prop that stores the default language of text selection. It's the single most important parameter that describes a default language setting used for text selection. The current language will be applied to text selection if there is no language information in the text's HTML element or its parents.
The current language will be updated every time a lexical query is started with the language different from
the current value of the current language.

Text language is a UI controller parameter that allows the host application to override the default language of text selection.
Preferred language is a default value for a text language of a page. It is set in the settings tab of an application.
Preferred language setting may be hidden in some modes.

If text language is provided then during an app initialization current language will be set to whatever value the text language holds.
Otherwise, current language will be set to the value of the preferred language.

Thus, the text language, if provided, has a priority over the preferred language. However, if user changes preferred language through the setting tab, a current language value will be set to the updated value of the preferred language. Since then a value of a text language will never be used in an app. This makes sense as a way to allow users to override the current language value manually if its initial value was not set correctly.

For lookups initialized by the double-click on a word:
1. If there is a language in the word surrounding context, that surrounding context value be used.
2. If surrounding context provides no value, a current language value determined as described above
will be used.
3. If the surrounding context contains any language info this value will be used as the new value of the current language.

Lookup components with a language selector:
1. If any lookup language is selected, the selected language will be used for the lookup request.
2. If the default value is selected, the current language value will be used for the lookup request.
3. The language used for the lookup request will be used as the new value of the current language.

Lookups without a language selector (are initialized with `usePageLangPrefs` option):
1. Will always use a current language value.
2. The language used for the lookup request will be used as the new value of the current language.

Lookup language parameter. Specifies which language is selected in the language drop-down in the lookup initially.
Initial value:
 - If `usePageLangPrefs` option of the lookup component is set, then it will be set to the value of the preferred language (not the current language value - do we need to amend this?)
 - Otherwise, it will be set to the value of `lookupLanguage` from the local or remote storage.
 Lookup language is updated only when user changes it via a drop-down. In all other situations it will stay as it was before.
 Lookup language is synced across all lookup instances with a language drop-down.

@balmas, does the above seems correct? Do we need to change the lookup language when the current language value has been changed?

**Comment by balmas** [comment]
Sorry, I need to diagram in order to make sense of it :-) 

So I *think* this is how the decision for which language to use to do a lookup should be decided:

![currentlanguage](https://user-images.githubusercontent.com/644870/61383655-19476b00-a87d-11e9-98ef-92a23aa4720a.png)

```
@startuml

start

if (selectedWordFromText?) then (yes)
  if (languageFromContext?) then (yes)
    :lookupLanguage = contextLanguage;
  else if (textLanguage?) then (yes)
    :lookupLanguage = textLanguage;
  else (no)
    :lookupLanguage = preferredLanguage;
  endif
else (no)
  if (haveLanguageSelector?) then (yes)
    :lookupLanguage = selectedLanguage;  
  else (no)
    if (textLanguage?) then (yes)
      :lookupLanguage = textLanguage;
    else (no)
      :lookupLanguage = preferredLanguage;
    endif
  endif
endif
  :currentLanguage = lookupLanguage;
stop

@enduml

```

**Comment by balmas** [comment]
Leaving aside for a minute the question of how to determine what should be the default language selected in the language selector, I think this implies some differences in what you have stated above (and maybe in our current code so it's just for discussion right now)

currentLanguage is a state variable that is used to keep track of the language of the last word looked up so that we can make sure the languages of all the shown resources are in sync.  It should *not* dictate the language of the next lookup, no matter what lookup mechanism is used.

**Comment by balmas** [comment]
The only setting that gets stored to user preferences is *preferredLanguage*

**Comment by kirlat** [comment]
> Sorry, I need to diagram in order to make sense of it :-)

Thanks for the great diagram, I will meditate over it for a while 🙂. I think we shall put a final version of it into the docs.

**Comment by balmas** [comment]
The default selected value for the language selector when shown next to a lookup box probably needs to be managed by state:

So, assuming a variable *selectedLookupLanguage*, I think the decision tree would be the following:

![selected](https://user-images.githubusercontent.com/644870/61386126-b0aebd00-a881-11e9-911e-18b4965414ec.png)

```
@startuml

start

if (selectedLookupLanguage?) then (yes)
  :defaultSelected = selectedLookupLanguage;
else if (textLanguage?) then (yes)
  :defaultSelected = textLanguage;
else (no)
  :defaultSelected = preferredLanguage;
endif

stop

@enduml

```

and on selection of a language, the state variable for selectedLookupLanguage should be updated.

**Comment by balmas** [comment]
let me know if this makes sense and if I have missed anything from your points above. 

thanks!

**Comment by kirlat** [comment]
I think we should expand this part of the first diagram:
![image](https://user-images.githubusercontent.com/18631055/61389654-5423c000-a8ca-11e9-84e4-70684d5fccd2.png)
That's when there is a language selector in the lookup, but the value of that selector is "Default". That's a valid case too.

**Comment by balmas** [comment]
I am wondering if that is an option we should keep though? It seems like it adds more complexity than is helpful.

**Comment by kirlat** [comment]
> The only setting that gets stored to user preferences is **preferredLanguage**

Right now we store the lookupLanguage (the language last selected in the language drop-down of a Lookup component) too, but maybe it's by accident. We use the stored value to initialize the drop-down selector to the last value selected by the user. Shall we stop storing it? If so, to what value shall a language drop-down in the Lookup component be set initially (i.e. when the app is loaded for the first time)?

**Comment by balmas** [comment]
I think we were doing that as a replacement for state. Now that we have the Vuex state it probably makes more sense to store it there.

I was thinking that the initial value should be as in the diagram in https://github.com/alpheios-project/components/issues/509#issuecomment-512292989  .. i.e if textLanguage is set, then that, otherwise preferredLanguage

**Comment by kirlat** [comment]
> I am wondering if that is an option we should keep though? It seems like it adds more complexity than is helpful.

It is complex indeed! Right now the role of the "Default" option is to let user not to worry about what language to choose but rely on system preferences instead. It is effectively disables a language selector as if it would not exist. This may make sense in certain scenarios to me and may not in other. If the user will employ a lookup component to query a specific word on a language known to a user, then user will be able to set the language manually. There is no room for a "Default" value in that case. But if the user have some word he/she wants to request and he does not know its language and wants to rely on some system settings for language detection (which may or may not make sense in this context), then a "Default" value may have its place. But I'm not sure if such scenario is reasonable.

**Comment by balmas** [comment]
>Right now the role of the "Default" option is to let user not to worry about what language to choose but rely on system preferences instead. It is effectively disables a language selector as if it would not exist. This may make sense in certain scenarios to me and may not in other.

I think this makes less sense now that we offer the quick access to the lookup on the toolbar without the language selector. That is effectively the same as the "default" option was before. Now, the only reason to use the lookup on the panel with the language selector is when the "default" option isn't what the user wants. So I say we should drop it from there and simplify things. Do you agree?

**Comment by kirlat** [comment]
> So I say we should drop it from there and simplify things. Do you agree?

Yes, that makes sense.

**Comment by kirlat** [comment]
I remember we were discussing that if the textLanguage is set we will never display a preferredLanguage option on the settings page. But that might change in the future, so we probably better design it now keeping in mind that a user might be able to change the preferredLanguage while textLanguage is used. What will happen with the textLanguage then?

I see two viable options here:
1. Keep things as they are now with textLanguage always taking priority over the preferredLanguage. In that case, however, changing prefferredLanguage will have no effect whatsoever. That will be a clear case for user confusion.
2. Once the preferredLanguage is changed, it will take the lead over the textLanguage. In that case textLanguage will be used to set just the initial language value with user being able to override it by changing the preferredLanguage value.
What makes more sense, on your opinion? Are there any other options?

**Comment by balmas** [comment]
I think the latter (#2) makes more sense and would be fine for now.

**Comment by kirlat** [comment]
Changes has been merged into master and are ready to be tested

**Comment by balmas** [comment]
in qa-3.0.0.47/components 1.2.6

**Comment by balmas** [comment]
although to fully test this, alpheios-project/alpheios_nemo_ui#227

**Comment by monzug** [comment]
the way it works right now is that when I go to latin authors, works and text, the lookup is set to Latin (which is also the default language). when I go to greek authors, works and text, the lookup is set to Greek.
if page language is set to Greek and I go to latin authors or works or text, the lookup is still latin and the double click recorgnizes latin as the language to use. looks like textlanguage as priority on pagelanguage. @balmas?
tested in text env

**Comment by balmas** [comment]
yes, that is how it is supposed to work. thank you.
