### ISSUE TITLE
condense the display of options

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#52]
requested by @abrasax 

put the option label on the same line as the dropdowns
for lexicon defaults don't show the full list open (but still handle multiselect well)

**Comment by balmas** [comment]
@kirlat when working on this try to make it responsive for mobile. it's possible for mobile we will want popup menus or some other mobile-friendly paradigm, I'm not sure. it needs some experimenting.

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/112

1) put the option label on the same line as the dropdowns - DONE
![image](https://user-images.githubusercontent.com/12377640/41329157-56b5b198-6f0f-11e8-9490-000c9268f2f6.png)

**Comment by irina060981** [comment]
2. for lexicon defaults don't show the full list open (but still handle multiselect well)
May be we should use this -
https://vue-multiselect.js.org/#sub-multiple-select ?

**Comment by balmas** [comment]
sure that looks like a good idea

**Comment by irina060981** [comment]
Ok - I have applied this multiselect component
![image](https://user-images.githubusercontent.com/12377640/41404898-c20a9600-700b-11e8-85e8-333cf69e63ef.png)

**Comment by balmas** [comment]
I think it looks good in your screen shot. But am seeing some problems with the font-size icons in my build:

![options](https://user-images.githubusercontent.com/644870/41559321-b27d39fa-7311-11e8-9a3a-3f4c85324af7.png)

**Comment by irina060981** [comment]
https://github.com/alpheios-project/components/pull/112
I have made a local merge to master and resolve all conflicts (including changes to styles).
Then I have tested it in embedded and in web-extension.
And I wasn't able to reproduce the bug you screenshot.

![image](https://user-images.githubusercontent.com/12377640/41572272-683cbc0e-73ba-11e8-8844-6e5345c8658d.png)

![image](https://user-images.githubusercontent.com/12377640/41572453-37caf170-73bb-11e8-8ac2-b08081520a71.png)

It seems to me that the bug is solved.
But may be you used it in some other environment?

**Comment by balmas** [comment]
Ah, the problem is related to that described in #115. On the page I'm testing with (http://www.thelatinlibrary.com/apuleius/apuleius4.shtml) that page has styles defined for the `li` element which are impacting the way that element appears on the page. I'm entered #121 for it, because it's unrelated to this one.

**Comment by irina060981** [comment]
I have added fixes for reskin panel styles.
![image](https://user-images.githubusercontent.com/12377640/41636677-3cef1aae-7493-11e8-9095-c7e3de3167d9.png)

**Comment by irina060981** [comment]
Merged and closed
