### ISSUE TITLE
requirement: store settings prefs with user data

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#522]
this needs to be scoped more fully so just a placeholder issue for now -- we will need to store user preferences data

**Comment by balmas** [comment]
I was hoping to do a full refactoring of the way we handle the settings before we added this feature, but I think we don't have time right now so I would like to go for a more minimal approach. 

**Storage**
I would like to use the Auth0 Management API and store user preferences as User Metadata 
(https://auth0.com/docs/users/concepts/overview-user-metadata). We will use one metadata property per setting.  We should use the options domain when storing settings so that we can easily differentiate from other sorts of metadata, should we decide to add that in the future.  

**UIController/Components Design**

1. Add methods for CRUD of user settings to the AuthModule api

2. Create a new AuthStorageAdapter derivation of StorageAdapter which delegates to AuthModule for CRUD of user settings

3. Upon login, instantiate an instance of the AuthStorageAdapter class and  reinitialize the options objects with the new storage adapter instance

4. For duration of the user session, changes to settings only get stored as user metadata

5. Upon logout, reinitialize the options objects with the storage adapter assigned to the ui controller.

**Comment by balmas** [comment]
@kirlat and @irina060981 please let me know what you think of this approach.

**Comment by kirlat** [comment]
To me, it sounds like a very good plan. Here are some additional thoughts about details of implementation.

a. The use of domain is very important. This will give us some piece of mind in isolating data of one type from the other.

b. I think it is also important to establish a versioning schema for options. Let's say we decided to change the way we store UI options and retarget some existing options for a different purpose. With embed lib it will be possible that there will be clients using different versions (old and new) of the embed lib at the same time. It can even be one client using different versions of embed lib running from different sites at the same time. Because of this, we shall provide a way for both new and old options to be used simultaneously. We probably do not need something as complex as semver. A simple integer value shall work for us, most likely.

c. On my opinion, it would probably make sense to version a domain, not individual key. This is simpler: each domain of a certain version will define a set of keys and their values. Changing a domain version will allow us to redefine those keys to something completely different, if necessary, without changing a domain name.

d. The simplest way to go with naming is probably to encode both domain and the version within the option's key. We could store key as something like: domainName__V2__keyName. That's easy to read, understand, and parse automatically.

e. It might be beneficial to allow to specify several storage adapters for a domain at once. This can simplify the use of options by automating the handling of storage switching. To implement this, an options constructor can take an array of storage adapters instead of a singe adapter as now. Let's say it takes LocalStorage and AuthStorage adapters. When we want to store an option, it will check each storage adapter if it is available, and will write data to all storages that are ready to be used. So in the example above, when user is logged out, options data will be written to the LocalStorage only. But once user will log in, data will be saved to both Local and Auth storages. For that, we have to add active/inactive state to each storage adapter.

f. I think we probably still need to keep a list of allowed values for each option somewhere and probably option's data type as well (and maybe a default value too). This is useful for both the purposes of documentation and as an additional control that can be applied upon the process of data updates. Probably we can use some JSON schema to describe that. It can contain a list of all options per combination of a domain and a version number. We can store this schema within the Alpheios app's code base and redistribute with the app.

What do you think about that? Does it make sense?

**Comment by balmas** [comment]
>d. The simplest way to go with naming is probably to encode both domain and the version within the option's key. We could store key as something like: domainName__V2__keyName. That's easy to read, understand, and parse automatically.

Agree with this approach.

**Comment by balmas** [comment]
>e. It might be beneficial to allow to specify several storage adapters for a domain at once

I thought about this, and it was what I was originally thinking of. I think the possibility to have multiple adapters is a good design, however, in this particular use case, I think we would probably not always want to save to local storage (or sync storage) while operating as a specific user. The reason for this is that a computer might be used as a shared workstation, in which case any setting changes made while a user is logged in should not filter down to the shared stored. We might want to support both possibilities by having a setting for that -- i.e. a switch to indicate whether or not the installation is a shared workstation, but I am not sure if it is 100% necessary right now

**Comment by balmas** [comment]
>f. I think we probably still need to keep a list of allowed values for each option somewhere and probably option's data type as well (and maybe a default value too). 

We do already have this don't we, in the default json files for each setting category?

**Comment by irina060981** [comment]
I like these approaches - I think it looks well!

I have only one note here - if we have more than one target to save data abd restore data - local and remote, or one user could have different versions of saved properties (I mean different versions of saved domains), than we should have defined sync process inside some adapter to define the priority of data (if they are different) and merge methods.

**Comment by kirlat** [comment]
> We do already have this don't we, in the default json files for each setting category?

This is correct. I just wanted to stress out that it would be good to keep it with this update, and extend the data stored with the version number, which we currently do not have.

**Comment by kirlat** [comment]
> if we have more than one target to save data abd restore data - local and remote, or one user could have different versions of saved properties (I mean different versions of saved domains), than we should have defined sync process inside some adapter to define the priority of data (if they are different) and merge methods.

I think we probably don't need to sync data between different versions. One time conversion, when user switches to the newer version of options, might be enough. Then both old and new versions can coexist, on my opinion.

Here is a usage scenario to illustrate the above.
1. User is working with V2 of the options through the older version of an embed-lib.
2. User starts to use a new version of embed-lib on a new site. This embed-lib uses options V3.
3. The new version of embed-lib discovers that there is no options stored for V3, but there are options for V2 in the storage.
4. The new version of embed-lib starts a conversion process, creating a set of V3 options out of V2 ones.
5. The new version of embed-lib stores V3 options to storage, keeping V2 options as well.
6. The new version of embed-lib from now on works with the V3 options only, ignoring V2 completely.
7. The old version of embed-lib is working with V2 options, ignoring V3 completely (because it has no knowledge of what V3 is at all).

Important question is how to cleanup old versions of options. We could probably keep them forever, considering that the size of data stored is not significant. Or we can probably erase old versions of option after some period of inactivity that is large enough (say, if nobody used them a year).

What do you think about that strategy?

**Comment by balmas** [comment]
I think that sounds good.  We do need to add an ability to remove all user data, including the account (see #601 ) and we should also allow them to reset their settings back to default (see #488).  I think expiring old versions might also be good, but think that it can be postponed until we actually have a new version of settings.

**Comment by balmas** [comment]
this is implemented now 3.0.0.45/1.0.0.27

Upon login, settings are reloaded from any stored user settings (and if none exist, then from defaults). Upon logout, settings are reloaded from the last local (for the embed-lib/texts) or browser sync storage (for the webextension).

In that way, any settings stored with the browser are shared settings for any user of the browser and the settings stored with the user are specific to that user's login.  Changes to a setting when logged in as a user won't impact the local storage and vice-versa.

**Comment by monzug** [comment]
test the following on FF:
on login, new user  A has default settings, then change setting and log out. 
on logout, the local settings are used. login as user B with its own settings. logout, local setting are used.

**Comment by monzug** [comment]
question: if I change a setting on one tab (not login), how does the browser sync propagate to the other tabs on web ext? right now, I have to reload the tab for the changes to take effect.

**Comment by balmas** [comment]
>question 1): if I change a setting on one tab (not login), how does the browser sync propagate to the other tabs on web ext? right now, I have to reload the tab for the changes to take effect.

This was by design (I think). If the user was using latin happily in one tab, and needed to change to greek in another, we didn't want the tabs fighting over it.

**Comment by balmas** [comment]
>question 2): in text env, the last saved settings are applied both for logged in or not login user.
to repro: I changed settings as a not logged in user. then I logged in with a different set of settings (default settings) but the local one override the logged in user settings. if I change back to default then the default will be used when I logged out.

this is is not expected behavior, so I will look into fixing it.

**Comment by balmas** [comment]
@irina060981 would you mind debugging this? Thank you.

**Comment by irina060981** [comment]
I have tested inside webextension - Chrome and Firefox
there is no this bug there - I tested with enable concordance settings.
Logged and not logged has different values, the only moment here - when you log in - you should wait nfro a second until it uploads the settings

**Comment by irina060981** [comment]
On https://texts-test.alpheios.net/ this bug is easily reproducable.

**Comment by irina060981** [comment]
But I couldn't check it with the current version (`master`) version of `embed-lib` and `components`.
Because 
    - it doesn't create AuthModule - current `env.js` in `alpheios_nemo_ui` doesn't have both `CLIENT_ID` and `LOGIN_URL` but we pass authEnv;
     - and embedded.js creates AuthModule only if there are one of `CLIENT_ID` and `LOGIN_URL`;

      in our case it doesn't print a error (it has `authEnv`) and doesn't create auth at all (`authEnv` doesn't have constants)

Finally it fails with errors (because there is not expected to have no auth at all).
I could create auth as it doesn't pass `authEnv` this way:
```
this.ui.registerModule(components.AuthModule, { auth: null })
```

But then login/logout is not accessable (similiar as it is in embedded-lib)

So I believe that https://texts-test.alpheios.net/ doesn't have the fresh version of components, as this error is absent in webextension, may be it is already fixed.

But I couldn't check because I don't know correct properties for the embed-lib.

I don't know what else I could here.

@balmas and @kirlat , what do you think?

**Comment by kirlat** [comment]
@irina060981: I think as Nemo UI uses an embed lib, it is better to test with embed-lib or even better with the local version of the Nemo UI. In the `protected-config` repository there are prod configurations for both Nemo UI and the embed-lib. I'm wondering if using those would allow to emulate the Alpheios text environment.

**Comment by irina060981** [comment]
alpheios-nemo-ui loads config from env.js, as I could see from the code.
Also Embed-lib doesn't work with authentication for some time - Bridget turned off notifications for that.
Let's wait for Bridget then - as I couldn't even understand how it was working before :)

**Comment by balmas** [comment]
sorry both. I will look at this tomorrow. thanks!

**Comment by balmas** [comment]
my error. I forgot to update the texts environment with the configuration for the user settings api.  Sorry !

(This is managed by the alpheios puppet scripts, https://github.com/alpheios-project/puppet/blob/texts-pwa/site-modules/capitains/manifests/init.pp#L70-L77 - we're operating off the poorly named texts-pwa branch for the test environment right now)

@monzug please retest now. Thank you!

**Comment by monzug** [comment]
it works in text env too. tested in Chrome on desktop and safari on iphone xr.

one issue here: when changing from latin to greek language, the first pop-up does not have definition. see screenshot
![greek-no found](https://user-images.githubusercontent.com/41396793/63434601-6c1fbf80-c3f3-11e9-9ca3-3f37491acaf2.JPG)

scenario: have options set to no lexicons, page language latin. login as user A with default settings
do a lookup in latin text then switch to greek text. note that the first lookups go from large font to medium font, briefly. The first greek lookup will not have definitions, only from second lookup on the definitions are generated.
Could it be that local Options bleeds into the user A options?

**Comment by balmas** [comment]
I'm not sure, but this might be a symptom of #751 . Will investigate.

**Comment by monzug** [comment]
not sure as there is also the font changing size

**Comment by balmas** [comment]
hmm I missed that but I'm not sure I understand.  Do you have the font-size set to large before login?

**Comment by monzug** [comment]
yes large before login then default settings when logged in so medium

**Comment by balmas** [comment]
ok. I think it could be a timing issue.   The requests are all asynchronous. I.e. after you login, we issue an async request to the user settings service to retrieve your settings and then reload them. So if you managed to sneak in a lookup immediately after login, before the settings have been retrieved and reloaded, it's possible you could get a lookup result which used the pre-login settings.

We could set a state variable to prevent lookups in that interim period, but I'm not sure if it's worth it. I could see that causing other complications. I think I'd like to postpone it to see if we get user reports of this issue. What do you think?

**Comment by monzug** [comment]
I am ok with it. I just wanted to report it

**Comment by balmas** [comment]
ok, I will make that a new issue so we can close this one.
