### ISSUE TITLE
bootstrap styles bleeding through on a elements

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#527]
when used on a page with bootstrap (such as alpheios_nemo_ui), the following style is overriding our link style (reproducible with the Credits 'show' link on the popup:

```
a:not([href]):not([tabindex]) {
    color: inherit;
    text-decoration: none;
}
```

I guess we need an important! on our styles here?

**Comment by irina060981** [comment]
I suggest to redefine bootstrap global properties for the links without href, because we could have much of them.
I have created `bootstrap.scss` insise scss folder, adds links to all files for building bootstrap from `node-modules` besides the one - `_reboot.scss`, where I have removed the following styles:
```
a:not([href]):not([tabindex]) {
  color: inherit;
  text-decoration: none;

  @include hover-focus {
    color: inherit;
    text-decoration: none;
  }

  &:focus {
    outline: 0;
  }
}
```

Later we could remove those bootstrap scss files we don't use (for example carousel)

**Comment by irina060981** [comment]
merged and closed
