### ISSUE TITLE
Grammar panel with double scroll bar

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#582]
Just notice that in build 3.0.0.36  and in text env in 1.0.0.14, the Grammar panel has two scroll bar in some specific scenarios.  Tested in Chrome and Firefox. 
to repro: from define panel, enter 'partir' in lookup. the morphological popup is generated with no entry. click on define and then on Grammar. the panel opens with two scroll bars.
see screenshot

![double-scroll-bar](https://user-images.githubusercontent.com/41396793/58339997-ca4efd80-7e18-11e9-93a5-4fc8f8f82e67.JPG)

**Comment by balmas** [comment]
not critical for beta

**Comment by irina060981** [comment]
As I could see - that is because the notification layout - it makes the panel has not enough space for credits - and it makes the second scroll bar (for the panel) to appear.
If you close a notification - it will have enough space and only one scroll bar for the grammar iframe

![image](https://user-images.githubusercontent.com/12377640/58362658-def4c980-7edc-11e9-9f54-41e9c3d93bc6.png)

**Comment by irina060981** [comment]
Merged and closed

**Comment by monzug** [comment]
tested in build 3.0.0.39 Firefox and Chrome + text env 1.0.0.21
looks good. Thanks
