### ISSUE TITLE
Firefox and Chrome: activate Alpheios, the overlay is not generated, need to reload

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#586]
latest build 3.0.0.37 in Chrome and Firefox. activate Alpheios, the overlay is not generated or there is a delay, for some sites. after reloading the page, all works well. any subsequent deactivation /activation, the overlay shows up right away. sites like latin library, Wikipedia, Scaife.

**Comment by balmas** [comment]
not critical for the beta release, which doesn't include the webextension but should fix soon

**Comment by kirlat** [comment]
@monzug, is this for the embedded lib or for the webextension? If it's for the former, then maybe it is related to the time required to initially load all the files that embedded lib needs. Right now it's around 5 MB of data, so it may take some time to get them. Once downloaded, this data is cached. That's why it might show fast on subsequent activations and deactivations.

But it's a wild guess and it as well might be something else.

**Comment by balmas** [comment]
I believe this was about the webextension.

**Comment by kirlat** [comment]
I did a lot of testing with webextension, and I never was able to reproduce a case when the overlay was not showing. It was always showing a panel after the extension was activated. 

However, I've observed a noticeable delay before the panel is shown. I've investigated the source of that, and figured out it's due to two factors: the page slow loading (some pages can take more than ten seconds to load) and the delay caused by the panel's `init()` function. The latter was taking up to 3 seconds in my tests.

Delay caused by the slow page rendering is especially noticeable when extension is activated and the page is refreshed. Because we're using `webNavigation.onCompleted` callback to start extension's re-initialization, and that event happens when a page and all its linked resources are fully loaded, it can take a significant time before the panel will be shown after reload.

However, page loading time is out of our control.

Trying to see what causes a delay inside the panel's init function, I discovered that this is because of the inflection browser. The views are rendered on demand, when each view is opened. Because of that, view rendeing does not delay the panel initialization. What does, however, are two functions inside inflection tables library, `createStandardFormHomonym()` and `getInflectionsData()`. While former takes up to 50 ms to execute, the latter takes longer, up to 200 ms. Those functions are necessary to construct a view object for each standard form view, and they are called for each view object before the view can even be rendered. Considering we have 118 view objects on the page, all those calls can take a lot of time to complete!

I'm looking for ways to speed those functions up and, thus, reduce the overall panel loading time.

**Comment by monzug** [comment]
Thanks for looking into the delay!!! my experience was with new installed webextension, after that activation/deactivation worked fine. will try in new build.

**Comment by monzug** [comment]
Re-tested in build 3.0.0.39 in Chrome and Firefox, the overlay is generated also on first activation of Alpheios. there is a delay more noticeable in some sites (e.g. Scaife) than eithers

**Comment by kirlat** [comment]
I think it's taking longer on some sites because Alpheios code and the other code that is loading on the page, while executing simultaneously (because JS is single-threaded), will compete for the same limited amount of resources of the CPU. So on sites where the page rendering involves some extensive calculation and taking, let's say 70% of the CPU time, there is only 30% left to the Alpheios code. So an Alpheios initialization will take three times more time than if all resources be available too it.

It's also a matter of how powerful a CPU of a device is and some other factors. The bottleneck here is computing power only, there almost no other factors involved, as it seems from my tests. So the more CPU resource Alpheios code will have, the faster it will complete its initialization.

I did not find any evident issues with the inflection tables' code. Building a table requires processing a lot of info, and it takes time. I will try to shift all calculations to the moment when inflection table is expanded and see how well will it work.

**Comment by balmas** [comment]
Maybe also consider #408 when working on this?

**Comment by kirlat** [comment]
> Maybe also consider #408 when working on this?

Great idea, I think there can be a solution to satisfy both.

**Comment by balmas** [comment]
embed-lib 1.0.0.24/webextension 3.0.0.41

@monzug this requires a regression of the inflection table browser, because it touched every table.

**Comment by monzug** [comment]
I will assign this to @balmas after today's discussion.  I did experience in build 3.0.0.41 that the overlay was not generated after installation. I needed to reload the page to see the floating tools.
see screenshot (both in Chrome and firefox) - as per @balmas suggestion, I did try without other text env tabs open with no luck. then I tried with reset all and restarting the browser and all works well. Some setting that is interfering?????

**Comment by kirlat** [comment]
I'm wondering if this happen because of authentication. I've seen some delays during test that were related to loading an Auth0 lock, or sending some authentication request to Auth0 (although this does not usually happen on initialization).

I can't think of any settings that might prevent an overlay from being shown.

Are there anything unusual in the logs in the browser console (error messages or warnings)? 

What would be the best way to reproduce the issue? Go to Wikipedia or Scaife, activate the webextension, and watch for no toolbar or panel appearing?

**Comment by balmas** [comment]
I was thinking maybe the Panel on Activate or some other setting was interfering. the fact that it resolved after she did the settings reset seems to confirm that.

**Comment by monzug** [comment]
why has it started in recent builds then? I haven't changed the way I do install builds in Chrome and firefox or the tabs that are already opened.

**Comment by balmas** [comment]
my hunch is that some, maybe now obsolete, setting is causing a javscript error that prevents the activation from completing.

**Comment by balmas** [comment]
would like to retest this in the next build, which cleaned up settings load.

**Comment by balmas** [comment]
Let's retest now in qa-3.0.0.46/embed-lib 1.0.0.28 (with components 1.2.2)

**Comment by monzug** [comment]
retested in 3.0.0.46. so far so good
