### ISSUE TITLE
all icons 22x22

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#609]
@abrasax requests that we make all icons 22x22 

unfortunately this conflicts with adherence to web accessibility standards but design is trumping accessiblity here.

I think right now they are already 22x22 everywhere except in the panel toolbars (both compact and full)

**Comment by balmas** [comment]
note :in check-in today we discussed the possibility of keeping the touchable area 44x44 but just reducing the icons.  We should try this, but note also #625 -- these may be conflicting requests.

**Comment by irina060981** [comment]
It starts to look a little strange :) 
(all of them are 22px, but because of shape they are not looked the same)

![image](https://user-images.githubusercontent.com/12377640/60439070-6ad4e080-9c55-11e9-9c56-fd09da44ec81.png)

![image](https://user-images.githubusercontent.com/12377640/60439366-141bd680-9c56-11e9-8176-f980b63fabca.png)

![image](https://user-images.githubusercontent.com/12377640/60439388-2269f280-9c56-11e9-80a9-6aa8ad5b48b8.png)

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
the space around the icons in the popup is not clickable. the @click handler needs to be moved I think.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
webextension qa-3.0.0.45/Safari3.0.0.45)/embed-lib 1.0.0.27

**Comment by monzug** [comment]
Is it only for the panel, correct?
I was checking the size of the Read icon, viewBox="0 0 30 27" or  Back to reader icon is viewBox="0 0 20 20". 

Definitely, by reducing the size we have now extra space on the compact panel. see Irina's screenshot. I would not recommend to move the icons around but it's not so pretty....

**Comment by balmas** [comment]
> Is it only for the panel, correct?
> I was checking the size of the Read icon, viewBox="0 0 30 27" or Back to reader icon is viewBox="0 0 20 20".
> 

It should be everywhere. Passing back to @irina060981 to confirm.

**Comment by monzug** [comment]
I looked in source view and that's the info I come up with. not sure if
viewbox is the right attribute for icon size

**Comment by irina060981** [comment]
`viewbox` is an attribute for the source svg - it defines the source propotions.
One of the important difference between SVG and other images formats is that SVG won't always have a clearely defined width, height and aspect ratio.
If we doesn't define width, height and viewbox - the browser will decide what sizes would be used for rendering SVG.

We define inside SVG images only a viewbox - to be able to scale it properly using css attributes width and height. `Viewbox` defines aspect ratio, initial placement of the svg objects by x, y axis and how it would be scaled inside SVG.

Width and height are defined using css attributes.
It could be checked this way:
for example back button on a grammar tab / mobile
![image](https://user-images.githubusercontent.com/12377640/61458337-9d007500-a9ad-11e9-9fe4-063af9c6ee49.png)

the current svg icon has width and height 22*22 (tooltip on the icon)
the whole button has - 32 * 32
the raw svg has a viewbox - `0 0 459 459`

That's why viebox could not be used for checking size.
I think the only correct way is to select it in the right panel (Elements of web inspector) and see the tooltip or see the computed css values - 
![image](https://user-images.githubusercontent.com/12377640/61458501-03859300-a9ae-11e9-94e3-49e0d558a50d.png)

@monzug, Hope it would be helpful!

**Comment by monzug** [comment]
absolutely!!!! Thanks.

**Comment by irina060981** [comment]
@monzug and @balmas , should I do something else here?

**Comment by balmas** [comment]
I don't think so @irina060981.

**Comment by balmas** [comment]
yes, let's let it go unverified.

**Comment by monzug** [comment]
cool
