### ISSUE TITLE
compact panel: navigation back to morphology from grammar

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#612]
when we implemented #564 we lost the ability to get back from a grammar link to the morphology (@irina060981 pointed this out but I missed the significance at the time...)

I think the simplest way to deal with this is to add a morphology icon to the compact panel navbar when navigating to the grammar panel from the morphology (but it would not be present when navigating from the action panel)

**Comment by irina060981** [comment]
I suggest to do it a little simplier and more predictable from my point of view

if there is no morph data than grammar tab has only this icon
![image](https://user-images.githubusercontent.com/12377640/59504688-d47b8d80-8ee6-11e9-9652-acdd3620c2b3.png)

if there is morph data, grammar tab has also morph icon
![image](https://user-images.githubusercontent.com/12377640/59504934-756a4880-8ee7-11e9-8f20-cb322572e7b7.png)

if do this way then - 
  - it would be more clear to user  (grammar tab has link to the last morph data always)
  - panel with main icons won't have grammar icon (because there is no additional space for it) - otherwise we should place it here to track what previous tab was active (so it won't be very consistent, that from morph tab we could go to the grammer but from definitions - it is not allowed)
   - a user could always get the last lookup results without redoing lexiqal request

Hope you will agree with my suggestion

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
ready for testing at texts-test embed-lib 1.0.0.23
webextension qa-3.0.0.40

**Comment by monzug** [comment]
good catch, Irina!!! now we do have the option to go back to morphology from the Grammar, except in the case in which we don't have any morphology result as for Cupidinesque
