### ISSUE TITLE
grammar index not displaying after first use

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#613]
at some point we lost the ability to get back to the grammar index. The first time you browse the grammar you get the index, but if you do a subsequent lookup and link to the grammar from the morphology there is no way to get back to the index.

**Comment by irina060981** [comment]
As I could see it works this way - 
   grammar index has url - https://grammars.alpheios.net/bennett/toc.htm?ts=1560750808070#alph-table-of-contents
   when you click and paragraph, you change the link for example to this
      Introduction—The Latin language -> https://grammars.alpheios.net/bennett/intro.htm
  
It seems to me that we could one of the following:
   1. refresh the iframe content on each opening grammar tab (could be not predictable for the user, as we refresh tabs on each lookup even if it is the same language and grammar)
    2. add back links to grammar pages

The 1. - is easier to do, 2. - is more predictable and useful for users.
What do you think, @balmas and @monzug ?

**Comment by monzug** [comment]
I don't think I have ever seen the intro page before!!!!!
I see the issue reported by Bridget (good catch). I checked Alpheios.net and the table of context is generated on every new lookup. Right now it's sticky to the last displayed section of the grammar.

**Comment by balmas** [comment]
For now, I'd like the grammar to open to the index whenever you access it from the browse grammar button on the toolbar and to the linked section when you open it by linking to it from the morphology details.  

In the future, we should consider adding better navigation within the grammar pages, but that will have to wait for now.

**Comment by irina060981** [comment]
I suggest to do this way - to add an icon - return to index like this
![image](https://user-images.githubusercontent.com/12377640/60086669-dcf18500-977e-11e9-9626-30b1a4e60f4a.png)

Because we have such situations:
1.
  - lookup a word
  - click on a grammar feature
  - opened grammar tab with data from grammar

if we connect refresh process to grammar tab, then it could be unpredictable for user 
    - a user need to close/open grammar tab to refresh
    - a user could simply select some other tab and return back to grammar - but see again index

2. Open grammar tab and click some index item - then to be able to return to index - a user should again close/open tab

It seems to me that home icon is more common use case.

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
in qa-3.0.0.42

**Comment by monzug** [comment]
two comments here:
1) can we change the home icon to a back arrow?
2) can we remove the back to index icon when I ma in index page?

**Comment by irina060981** [comment]
>can we remove the back to index icon when I am on a  index page?

It is not really an easy task
because we don't have states for the url

There are  two workflows:
**the first**
   - on  lookup a word we define the language and request grammar for this language
   - after that we have grammar index on the tab 
   - then the user could click links and go to other parts - but the link of iframe is not changing
    so it is not really easy to track - that the user is not already on the index
    but if we could somehow (I don't know how) track that it changes - we could reload the whole iframe and it would return to the index   

**the second**
   - a user clicks on some grammar link in the popup
   - it rerequest the current page of the grammar and loads it to the iframe - and it would be considered as **index** 
    and we won't be able to simply reload the page, we would need to fully rerequest the grammar tab 

that's why I simply placed a home button here :)

**Comment by monzug** [comment]
I see.  same as why we can't go back to index.
as per icon, can we change to a back arrow?

**Comment by irina060981** [comment]
yes, I could!
Why I placed home icon - because I started from the second scenario
when I first open the grammar for the feature from popup
and I thought about back icon, but in this case - back icon could be not very clear

but if you think that back icon is better - I will change of course

**Comment by monzug** [comment]
I think so. if you don't mind, let's give a try

**Comment by irina060981** [comment]
would be this way
![Uploading image.png…]()

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
embed-lib 1.0.0.25/webext qa-3.0.0.43

**Comment by monzug** [comment]
back icon is there. Thanks.

I noticed that the link to grammar from morphology are different in desktop versus mobile.
e.g.  collaudatur  in https://texts-beta.alpheios.net/text/urn:cts:latinLit:phi0448.phi002.perseus-lat2/passage/1.1.1-1.1.4
click on 1st conjugation from morphology. in desktop it will take the user to the FIRST (OR Ā-) CONJUGATION of the Grammar
on mobile, it will stay in Part II, Inflections without taking the user to the chapter.

**Comment by balmas** [comment]
hmm, that's interesting. On the Galaxy 7 it does first go to Inflections and then, after a moment, to First Conjugation.  Surprised that this would behave differently on the iPhone because it's just standard link hash reference.  Are you sure it doesn't go to the section after first loading the page?

**Comment by monzug** [comment]
I waited for a bit but didn't go anywhere.

**Comment by balmas** [comment]
ok. converting to a new issue. Will investigate.

**Comment by balmas** [comment]
entered as #655 
can we close this one?
