### ISSUE TITLE
usage examples: populate upon access

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#619]
Rather than offer a "Get Results" button on the Usage Examples page to retrieve the default unfiltered results, we should execute the search when the examples tab is accessed if results are not already available.

**Comment by irina060981** [comment]
Also I have removed the option - Get results without limits
as it lost any sense without a button.

**Comment by irina060981** [comment]
Merged and closed

**Comment by balmas** [comment]
embed-lib 1.0.0.24/webextension 3.0.0.41

**Comment by monzug** [comment]
OK, I don't mind this new redesign but I believe we cut few steps. Let me explain why.
Click on Show limits. we get the Limit these results by Author and/or Work with the option to select an Author or to select sorting type.  If I select an Author, it shows the results of the search without giving 
the possibility to select a textwork or to sort by. In order to do this I have to go back to show limits. Only at this point I do have the Author field populated and I can chose text work.
not sure if this is by requirement.

**Comment by balmas** [comment]
>f I select an Author, it shows the results of the search without giving the possibility to select a textwork or to sort by.

The limits are hidden by default after each search because they talk up a lot of room and on the mobile it's not immediately clear that any search was done.

**Comment by balmas** [comment]
I agree it would be nice to be able to select author and work in one step, but this was the workflow that @abrasax requested. 

Maybe on the desktop though we shouldn't hide the limits by default and only do that on mobile. What do you think?

**Comment by balmas** [comment]
see also comments in #620

**Comment by balmas** [comment]
think we can re-close this one. We now only show focus/sort options on mobile.
