### ISSUE TITLE
 User example: on mobile, source links are below the examples

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#635]
tested in text env  - User example: on the mobile we have the source links below the example., in text env on Chrome and Firefox, it's the opposite (source links above the examples). 
Source links should be above the examples.

**Comment by irina060981** [comment]
>tested in text env - User example: on the mobile we have the source links below the example., in text env on Chrome and Firefox, it's the opposite (source links above the examples).
Source links should be above the examples.

It was made by previous requirements, that's why we have it both in layout (before and after).
I am not against to place it always above, of course.

But I would like to notice it and re-check this new requirement :)
@balmas and @monzug , I should remove source link below the example on mobile, it should be always above - on desktop and mobile. Am I right?

P.S. We have so much changing requirements - we need to create some tag system to track such changes - I wasn't able to find that issue with the requirement to be below on mobile :) and I really don't know how to search for it - because we change assignments and doesn't have tags by type.
@balmas, @monzug, @kirlat , what do you think?

**Comment by monzug** [comment]
I didn't know there was a requirement to be below on mobile. I looked on old posts and issues, as you said I could not find much info. I tend to rely on @balmas, she knows and remembers everything... but you are right, there should be a way to keep track of changes.

**Comment by balmas** [comment]
I don't remember EVERYTHING ;-) For example, I have no memory in this case of whether it was supposed to be above or below.  I don't know if it matters too much one way or another but maybe if there was a discussion about it, it was before we had the option to hide the source links?

I agree we could be better about tagging of issues, but no system is foolproof either.

**Comment by monzug** [comment]
you DO remember almost everything

**Comment by monzug** [comment]
anyhow, as we want to be consistent, there shouldn't be much difference between mobile and desktop

**Comment by balmas** [comment]
agree -- let's just move them above.

**Comment by irina060981** [comment]
Ok - suggest to make it this way
![image](https://user-images.githubusercontent.com/12377640/60172904-01b62d00-9851-11e9-9a9b-bf44c0c7c613.png)

May be it would be easier to scroll with it?
I have tested on my Iphone - scrolling is ok!

**Comment by irina060981** [comment]
merged and closed

**Comment by balmas** [comment]
embed-lib 1.0.0.25

**Comment by monzug** [comment]
thanks for moving the links above the examples. scrolling is still not good though....
