### ISSUE TITLE
replace "no lexical data" with a spinning wheel or other progress indicator

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#65]
while waiting for the popup to be populated, it would be better to show a spinning wheel or other progress indicator rather than the default "no lexical data" message.

**Comment by balmas** [comment]
This should also show the word that was identified and is in the process of being looked up.

**Comment by balmas** [comment]
@kirlat can you port the change you made for the pwa to the master components branch for this?

**Comment by kirlat** [comment]
Sure, will do that

**Comment by kirlat** [comment]
I've added a progress indicator similar to the one used in PWA, please check it out. The tag is `comp-i65`. A link to zip downloading: https://github.com/alpheios-project/components/archive/comp-i65.zip

**Comment by monzug** [comment]
got an error unpacking the build on chrome: could not load manifest

**Comment by kirlat** [comment]
Hi Monica, let me check it on my machine.

**Comment by monzug** [comment]
Thanks

**Comment by monzug** [comment]
Uhm, not crazy about this.
1) it's a long blue bar with inside some black marks. when loading really fast, it kind looks like overlapping some text, but those are just the black marks.
2) when double clicking on a greek word and latin is the default language (or a non existing word), it goes on and on and on for ever.  it's confusing for the user as he/she can get stuck there waiting for the loading bar to be done.

**Comment by balmas** [comment]
@kirlat returning to you to see if Monica's comments can be addressed.

**Comment by kirlat** [comment]
Can you please provide a example of how a progress bar looks with black marks? In my tests it was showin like below
![image](https://user-images.githubusercontent.com/18631055/45174908-17545a80-b21d-11e8-8a3b-f2efe850ecf7.png)
so I'm wondering if it is displayed correctly in your case.

Indicator has the same design we used in a PWA. I agree it might not be ideal (and I'm not a graphic designer), but I think a bar-style element fits well into a layout.

A moving indicator goes on forever because we cannot show a "real" progress as it depends on multiple requests to remote resources and it is hard to estimate how many we would have and how much share each one should have of a total progress. So the purpose of a current indicator is just to say: "hey, there is something going on, so please be patient".

I fixed an issue with progress indicator going on forever on unknown words (it was a problem in a code), please check an updated build:  https://github.com/alpheios-project/webextension/archive/comp-i65.zip

Do you have any ideas how a UI can be improved against what we have now? Thanks!

**Comment by balmas** [comment]
this looks okay to me too. Sometimes it's so quick that you can't really read the text, and maybe that's what @monzug is referring to as "black marks"? I'm not really sure how we could make this better. The bar could perhaps be a little smaller. Monica, do you have ideas of how this could be made better?

In the latest build I believe the 2nd problem (of endless loading with failed lookup) is fixed.

I do think we need to improve the error message in that case but I'm going to enter a separate issue for that because it's not related to this item and has a couple of parts to it.

**Comment by monzug** [comment]
it looks fine now. before I could not read the text inside, I could only see the top and did not look nice. Thanks for fixing the loading problem with unknown text.

**Comment by balmas** [comment]
Hi @irina060981 can you check this and see if you can add a fix to the comp-i65 branch for the style problem related to the site Monica gives as an example? Thanks!

**Comment by irina060981** [comment]
Fixed - Created PR - https://github.com/alpheios-project/components/pull/205
@monzug, this is a branch for testing - https://github.com/alpheios-project/webextension/tree/qa-progress-bar-issue

**Comment by monzug** [comment]
Irina,
I did install the build from https://github.com/alpheios-
project/webextension/tree/qa-progress-bar-issue but can't see the progress
bar just to old plain text. Pls advice. Thanks

**Comment by irina060981** [comment]
@monzug ,
I am sorry, I have forgot yo build the branch - I have done it now and tested - it works :)

**Comment by monzug** [comment]
Ok, please add label waiting_verification. Thanks

**Comment by irina060981** [comment]
Done

**Comment by irina060981** [comment]
@monzug , Monica - I have got an approval for my PR and merged all changes to master, so I remove developing branches.
Now this functionality is in master branch - so it could be checked in master - 
https://github.com/alpheios-project/webextension .

**Comment by balmas** [comment]
can be tested in https://github.com/alpheios-project/webextension/tree/qa-2.0.3-6

**Comment by monzug** [comment]
looks good to me. Thanks
