### ISSUE TITLE
iphone xr: Logged in but icon is grayed out

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#685]
tested in text env 1.0.0.28, on iPhone xr

I logged in from the Main Menu but the related icon in the tool bar is grayed out. see screenshot

![IMG_3712](https://user-images.githubusercontent.com/41396793/61409853-1b2b2180-a8b1-11e9-8f56-6f580a5827ba.PNG)

**Comment by balmas** [comment]
After debugging on the iPhone XR, I believe this is caused by the dynamic imports.

We load the authentication environment into a global variable (serverEnv) via the inclusion of an env.js using a `<script>` tag but it seems that on the IphoneXR at least, the dynamically imported embedded library code doesn't have access to that variable, so it doesn't setup the SessionAuthenticator.

@kirlat what do you think is the best way to solve this? We could dynamically import the env.js I guess, or maybe we pass the variable to the embed-lib constructor?

**Comment by kirlat** [comment]
On my opinion, passing an environment object to the embed-lib would be the best solution. If Embedded class is solely responsible for initializing a controller object, then it would make sense for the Embedded to check and verify that all necessary information is available before proceeding with the UI controller creation. Relying on the presence of the data in some window or global prop is too shaky, on my opinion. Even if we do that, it's probably good for Embedded to check if the data that is necessary to go ahead is there. If some data is missing, Embedded shall decide whether there is still enough info to proceed with the controller initialization and inform user about the issue.

If we use dynamic imports, and they seem to be working (at least as our tests show so far), it would make sense to use them for everything, on my opinion. That gives us more control to decide when exactly request to be done and analyze results of such request (success or failure). If we place env variables file to the remote server and load it from there, that will allow us to change environment keys without a need to update clients manually. Another option, maybe not very feasible right now, but still possible, would be to use CORS controls for the env file requests. We can set up a server with the sensitive env information so that it will analyze from what domain does a request comes from and based on that (and maybe even on some additional information that comes with this request) decide whether to allow this request or not. We could, for example, blacklist some IP addresses if we would need to do so. 

What do you think about this?

**Comment by balmas** [comment]
Thanks @kirlat . I agree. For the immediate term, I think we should pass the env file to the embed-lib and in the longer term, we should look at having finer-grained control of this by using a server.  I'll proceed with the former change for now.

**Comment by monzug** [comment]
also, the saved wordlist for the user is empty.

**Comment by balmas** [comment]
embed-lib 1.0.0.31

**Comment by monzug** [comment]
this works on Safari/iPhone xr
