### ISSUE TITLE
setting font size has no effect in Safari

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#758]
reported by @monzug 
seems to be true in both the webextension the texts environment. 

Maybe the font-size property on the html element doesn't work there?

@irina060981 can you investigate?

**Comment by irina060981** [comment]
As I could see from the code it was refactored and now font styles are changed through the variable.
`style="--alpheios-base-text-size:20px;"`

But it couldn't properly work on Safari, because of style priorities.
All styles are applied with `important` flag, so only changing the variable won't work at all.

To solve it - we should downgrade to the previous way of changing font-size (without variables).
Add the parent class and upgrade/doengrade font-size upon it.
It would need a deep refactor.

@balmas and @kirlat , what do you think about it?
It seems to me that we were talking about these problems while we discussing using css variables.
But I couldn't remember what solutions were suggested.

**Comment by balmas** [comment]
We cannot refactor this now, so if there isn't any other way to get this to work, I would suggest we just hide the resizing options on Safari.  They aren't important enough to delay over. But I'd like to see if @kirlat has any suggestions. (I tried putting an !important flag on the --alpheios-base-text-size style on the html element and and didn't have any effect)

**Comment by kirlat** [comment]
I will try to investigate it and find a way to do that without refactoring.

**Comment by kirlat** [comment]
I did some tests and it seems to me that the problem is that all CSS custom props (i.e. vars) has an `important` modifier on them. As a result of this, when we create a var with the modified font size value, it still has a lower priority than a default var value defined in a Safari stylesheet.

If to remove an `important` modifier from the vars in the Safari CSS stylesheet, the font adjustment starts to work (at least it did for me). @balmas, @irina060981, can you please confirm that this is the case for you? If so, the solution is to make sure a generated CSS file for Safari have no`important` on all of its CSS custom prop definitions.

**Comment by balmas** [comment]
yes that seems to fix the problem for me.  I think we should remove the !important flag from all of the alpheios css vars.

**Comment by balmas** [comment]
qa-3.0.0.57/components 1.2.27 (Safari build in Dropbox)

**Comment by monzug** [comment]
this works now
