### ISSUE TITLE
delay in generating the definition in pop-up

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#779]
it could be either this issue or #751. I have experienced a delay in generating the definition in pop-up. have to click on other words before getting the definition on the first one. to repro, clear cache and reload page, then go to
https://texts-test.alpheios.net/text/urn:cts:greekLit:tlg0085.tlg005.alpheios-text-grc1/passage/1-30
and double-click on τῶνδ᾽
it's on the first few lookups then the definition is generated

_Originally posted by @monzug in https://github.com/alpheios-project/client-adapters/issues/31#issuecomment-525775999_

**Comment by balmas** [comment]
but please test in later build, qa-3.0.0.61/components 1.2.33

**Comment by monzug** [comment]
honestly I am not crazy about this loading page. the reason is that we do have already a pop-up with lexical data is loading, then we get again a loading bar or more than one in the morphology pop-up. I have to say that the loading bar goes away super fast and usually it's only for the first few words. said so, I can live with it but could you check with Harry?
this is οἰχομένων in  Persians - Aeschylus

![lexical-data-is-loading-again](https://user-images.githubusercontent.com/41396793/63963888-f1dee300-ca63-11e9-9489-35d2342ec338.JPG)

**Comment by balmas** [comment]
Yes. Will show and discuss with @abrasax tomorrow

**Comment by monzug** [comment]
Thanks.

**Comment by balmas** [comment]
@abrasax agrees he can live with this too for the release. @monzug we can verify?

**Comment by monzug** [comment]
yes, verified
