### ISSUE TITLE
log in/out button has different style (super low priority)

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#791]
in https://www.loebclassics.com, the log in (and log out) button has different style. see screenshot

![log-in-loeb](https://user-images.githubusercontent.com/41396793/64626186-6ea28300-d3bb-11e9-8a02-85925351a0f2.JPG)

**Comment by balmas** [comment]
not sure we can do anything about this. If we can, I would not do a build only for this, but if other critical issues come up, we could sneak it in.

**Comment by monzug** [comment]
agree.

**Comment by irina060981** [comment]
It is because of `!important` styles
![image](https://user-images.githubusercontent.com/12377640/64660957-f5239700-d485-11e9-977c-0b9405867a79.png)

We were talking about such problems (important styles for the basic tags) and decided to leave it as is. Because it would need to use important from us - to basic tag and to all children styles.

**Comment by balmas** [comment]
right. okay, won't fix this one.
