### ISSUE TITLE
quaedam: takes forever for lexical data to load

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#797]
go to http://thelatinlibrary.com/gellius/gellius12.shtml and search for quaedam

whitaker returns the following:

quaedam
dam                  TACKON                             
PACKON w/qui => certain; a certain (one); a certain thing;
qu.ae                PRON   1 0 NOM P F                 
qu  PACK   [XXXBX]  
qu.ae                PRON   1 0 NOM S F                 
(w/-dam) certain; as INDEF a certain thing; somebody, one, something;

apparently we do not generate the information for dam and we keep loading lexical data

![Screen Shot 2019-09-11 at 4 10 27 PM](https://user-images.githubusercontent.com/41396793/64704586-d71e5c80-d4ae-11e9-8246-4a3b812f83cc.png)

**Comment by balmas** [comment]
another interesting safari error here:

[Error] Alpheios error: user data unexpected error - TypeError: undefined is not a function (near '...t of i...')
	forEach
	printErrors (content-safari.js:1:679188)
	(anonymous function) (content-safari.js:1:676808)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob

**Comment by balmas** [comment]
ok, thanks

**Comment by balmas** [comment]
yeah, something is going wrong here. 
We get responses from the morphology service with 3 possible lemmas, but only the first (qu) is displaying and that gets no entries from the lexicon service. the display is not getting updated properly and is missing information.

**Comment by balmas** [comment]
ok, this bug is caused by the fix for #779

We get one valid lemma from the morphology service.

That lemma does not have a short definition that we can find. 

And in that scenario, the loading message for the short definition isn't going away when it should, so it looks like it is loading forever, when in fact it is done, just not showing the no definition found message.

(Note that the fact that the morphology service actually returns 3 lemmas is a separate bug, but not new with this release so I'll enter an morphsvc bug for that)

**Comment by balmas** [comment]
see https://github.com/alpheios-project/morphsvc/issues/28 for the longer standing problem with the morphology service

**Comment by balmas** [comment]
qa-3.0.0.66/components 1.2.41

We still don't get definitions for this word, but that is the same as in 2.1.x. But the loading message is gone.

**Comment by balmas** [comment]
note @monzug when testing this, please do a quick regression on the wordlist too.
