### ISSUE TITLE
linked features not being applied in new morph component 

### ISSUE THREAD

**Issue by balmas** [alpheios-project/components#83]
the linked features aren't being applied properly in the new morph component after merge of #75 . Oddly, this seems not to be the case when used in the embedded library, only with the webextension.  Needs further investigation.
![metamorphoses liber iv](https://user-images.githubusercontent.com/644870/40443483-7795ae08-5e94-11e8-9ebd-894d636f22e6.png)

**Comment by irina060981** [comment]
Bridget, I couldn't reproduce this bug.
For testing - 
  1) I have updated all libs for webextension
  2) created a test page (from demo page of webextension) - http://alpheious-test.irina-sklyarova.ru/
      with this word - **ablative**
  3) uploaded webextesjon to firefox and opened this page
  4) and it shows all links
![image](https://user-images.githubusercontent.com/12377640/41022321-840aeafe-69ac-11e8-9fca-056516ff4372.png)

What should I do for reproducing? May be it was already fixed with some corrects for testing?
Could you reproduce?

**Comment by balmas** [comment]
hmm. I think you are right. I can't reproduce this either now. Possibly was an error with my build.  I'll close it. Thank you!
