### ISSUE TITLE
Chinese language morphology data

### ISSUE THREAD

**Issue by irina060981** [alpheios-project/components#843]
I decided to create issue here.
There are the following branch:
  https://github.com/alpheios-project/data-models/tree/test-chinese-language
  https://github.com/alpheios-project/client-adapters/tree/test-chinese-language     
  https://github.com/alpheios-project/components/tree/test-chinese-language

I tested it with the help of embed-lib.
It works from lookup component now
(remember, that I didn't format pinyin and radicals)

愛好者
![image](https://user-images.githubusercontent.com/12377640/67769930-132e7080-faa1-11e9-989c-26574fa6fd69.png)

 北京市
![image](https://user-images.githubusercontent.com/12377640/67769953-1f1a3280-faa1-11e9-821c-186e8627f270.png)

廣大地
![image](https://user-images.githubusercontent.com/12377640/67770005-3f49f180-faa1-11e9-8859-d3ad2d48af38.png)

**Comment by irina060981** [comment]
@balmas, I would be glad to get some feedback is this data extracted correctly.
It is correct amount of lexemes, lemmas
I am not sure why all features are the same

**Comment by irina060981** [comment]
@kirlat , may be it would be interesting for you too

**Comment by balmas** [comment]
@irina060981 this is awesome to see. I will look it it today!

**Comment by kirlat** [comment]
> @kirlat , may be it would be interesting for you too

Would be glad to look at that!

Do I understand correctly that the first word in `adso.dat` is in Traditional Chinese and the second one is in Simplified? Characters in both can be the same if they were not simplified. Is that correct?

**Comment by balmas** [comment]
I see it working in the embedded library :-) that is truly awesome

some initial feedback (without having looked too closely at the code yet)

Adapter/Chinese Data Model

1. Pronunciation
mandarin, tang, cantonese should not be features themselves, these all can go in the pronunciation feature (which should be multivalued). I think for now we could just include the classifier (Tang, Mandarin, Chinese) in the value string, just before the value itself (e.g. Mandarin GUANG3, etc.

Please also take a look at the `formatPinyin` method from the alpheios-chinese-dict.js (and how it is used there) because I think we want to format the pinyin and mandarin pronunciations with the unicode chars and tones

2. Radical
Including the radical will be important (this is how chinese words are looked up in a chinese dictionary). I think adding a separate feature for it like you have is the right way to go, but it needs to be populated (I think this is the hanziDat.RSUnicode field, and will need to be converted to unicode as per the `radicalIndexToChar` method from alpheios-chinese-dict.js. We should use the radical that corresponds with the input form (traditional or simplified)

3. Dialect
I don't know if dialect is the right feature to use for traditional vs simplified. Technically this isn't a dialectical feature. I would be inclined to just put it in the note field for now.

Otherwise, it looks to me so far like you are interpreting the data correctly. I see your point about the features -- I think this is because they are coming from the hanzi.dat file which appears to be specific to the characters (i.e. the homonym itself) and not the lexemes/i.e. meanings.    This might indicate a need to add features to the Homonym but before we go that direction I think we need to verify exactly what's in the hanzi.dat file.

I believe adso.dat is a version of CEDICT, which there is a newer version of now at  https://www.mdbg.net/chinese/dictionary?page=cc-cedict (see also https://cc-cedict.org/wiki/format:syntax)

Hanzi.dat was extracted from the UNIHAN database http://unicode.org/charts/unihan.html . We might want to compare your conversion of it with this library https://github.com/dahlia/unihan-json

**Comment by irina060981** [comment]
@balmas , I think - i have fixed upon your notices and added convertion method for pinyin, mandarin and radical
(I have updated branches)

Here are the examples
![image](https://user-images.githubusercontent.com/12377640/67857495-ad0a2200-fb62-11e9-9f5c-1c9fa0fd6c7f.png)

![image](https://user-images.githubusercontent.com/12377640/67857509-b7c4b700-fb62-11e9-9902-2481b3ce0855.png)

![image](https://user-images.githubusercontent.com/12377640/67857542-cf9c3b00-fb62-11e9-978c-3144590d4247.png)

**Comment by irina060981** [comment]
@balmas , I could start to work on selection (now it works only from lookup)
or may be there are some other steps - you think is more useful now?
Or may be you see some errors in the chinese morphology?

**Comment by balmas** [comment]
@irina060981 That's wonderful! Yes please go ahead to working on selection. Thank you so much.

**Comment by balmas** [comment]
@irina060981 please add contextForward to the parameters that are passed to the getHomonym method of the client adapter for chinese. See also alpheios-project/client-adapters#41. Thanks!

**Comment by irina060981** [comment]
The next step - added MouseMove event for chinese

**Comment by irina060981** [comment]
The next step is to add an ability to send several homonyms from the service and retrieve them inside components.
The discussion is here:
https://github.com/alpheios-project/client-adapters/issues/40
https://github.com/alpheios-project/components/issues/856

**Comment by irina060981** [comment]
For now it is merged to send all homonyms as lexemes for one target word

**Comment by balmas** [comment]
closing this one for now. Will be tested further with most recent chinese changes. New issues will be entered for outstanding features.
