### ISSUE TITLE
Loading or no definition found from limit by this session

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#851]
Several times today I ended up with a loading morphology pop-up or No definitions found. this is in Chrome, build Alpheios Reading Tools 3.0.3.87
to repro:
open the Latin library site and login as user test. then enter few Greek words in the lookup after changing the default language from Latin to Greek. from the inflection table panel select the User word list and limit by this session for the Greek words. double click on any of the words entered from lookup. Initially, I did have the loading morphology pop-up. after closing this pop-up, I double click on the same Greek word again, and got the No definition found. see screenshots.
all went back to normal after I double click on any Latin words from the Latin text.
![no-definitions-found](https://user-images.githubusercontent.com/41396793/68214469-848f8700-ffab-11e9-9f27-85046ce1686b.JPG)
![loading-popup](https://user-images.githubusercontent.com/41396793/68214470-848f8700-ffab-11e9-8b1d-ecb0e724a870.JPG)

**Comment by balmas** [comment]
hmm. that's interesting. I cannot reproduce so far. I am wondering if you can reproduce with lookups from the page rather than the wordlist. When you lookup a word from the current session in the wordlist, it should be pulling the definition from the in memory cache of the wordlist, and when you lookup from the page or a word on the list which is not from the current session, it should pull the short definition from the in memory cache of the short definition index.

Neither of these should be impacted by any load on the remote services.

**Comment by monzug** [comment]
retested in build 3.0.3.90 or 91. Occasionally I got the no definition found

**Comment by monzug** [comment]
Chrome ok
