### ISSUE TITLE
Randomly (latin) is added to the search word in morphology pop-up

### ISSUE THREAD

**Issue by monzug** [alpheios-project/components#860]
Bridget thinks "that there must be something in 
the css of the page -- it's there but hidden with css so if there is a 
conflict with the page css that could be the problem."
see screenshot

 
![Screen Shot 2019-11-19 at 4 38 31 PM](https://user-images.githubusercontent.com/41396793/69242002-f9e38600-0b6d-11ea-8578-36382b23ee86.png)

**Comment by balmas** [comment]
ohhh. I just looked at the code, and I see we display that if we are in Verbose Mode. @monzug I think you are sometimes switching verbose mode on and that might explain why you see it randomly.

I do think we should just get rid of this since we never really want to display it to the user and it isn't really necessary for debugging, but I don't think it's urgent.

**Comment by monzug** [comment]
that's why is 'randomly' generated. yes, I use verbose mode with some user.
absolutely the lowest priority! Thanks

**Comment by monzug** [comment]
interesting, I have verbose mode on but latin does not show up next to
search word.

**Comment by monzug** [comment]
it takes few lookup to kick in

**Comment by monzug** [comment]
I can still see the latin in normal mode
![Screen Shot 2019-11-20 at 3 43 23 PM](https://user-images.githubusercontent.com/41396793/69249311-f5d75880-0bad-11ea-8ebd-c4971fc2c741.png)

**Comment by balmas** [comment]
I think it's probably not a reactive setting -- i.e after you change it, you may need to refresh the page to see the difference.

**Comment by irina060981** [comment]
I have made this small fix
I think that we really don't need it in verbose mode :)

**Comment by balmas** [comment]
agreed!

**Comment by irina060981** [comment]
merged and closed
