### ISSUE TITLE
Broken Inflection Browser tests

### ISSUE THREAD

**Issue by kirlat** [alpheios-project/components#875]
In the latest commit of `master` (cbcb2b327afa93fc2311d465fdb3a1b7a9cf6db3) all but four tests in `inflections-browser-1.test.js` are broken. We need to find a reason why and fix them.

**Comment by irina060981** [comment]
There is only one problem here - it doesn't have enough time to render.
I believe that our code becomes bigger and bigger and Vue need more time to work with components.
By the way the inflection-browser check is excluded from the travis test - because it is too specific and too heavy for overall testing.

**Comment by kirlat** [comment]
> By the way the inflection-browser check is excluded from the travis test - because it is too specific and too heavy for overall testing.

Oh, I've missed that completely! I thought it was running a `test` task but after you've mentioned it I've realized `travis.yml` mentions `test-lib` and `test-components`. Then, I think, this test is not so urgent to fix.

> I believe that our code becomes bigger and bigger and Vue need more time to work with components.

100% agree with that. I think complexity of our builds and tests increased significantly and we should probably think about how to tame it before it will skyrocket and go out of control completely.

**Comment by irina060981** [comment]
Merged and closed
